/*
 * Сreated by Igor Pokrovsky. 2020/4/29
 */

package com.gmail.nigtime456.weatherapplication.testing

import com.gmail.nigtime456.weatherapplication.net.json.JsonCurrentForecast
import com.gmail.nigtime456.weatherapplication.net.json.JsonDailyForecast
import com.gmail.nigtime456.weatherapplication.net.json.JsonHourlyForecast
import com.google.gson.Gson


object FakeJsonDataProvider {
    private val gson = lazy {
        Gson()
    }

    fun getHourlyForecast(): JsonHourlyForecast =
        gson.value.fromJson<JsonHourlyForecast>(jsonHourly, JsonHourlyForecast::class.java)

    fun getDailyForecast(): JsonDailyForecast =
        gson.value.fromJson<JsonDailyForecast>(jsonDaily, JsonDailyForecast::class.java)

    fun getCurrentForecast(): JsonCurrentForecast =
        gson.value.fromJson<JsonCurrentForecast>(jsonCurrent, JsonCurrentForecast::class.java)


    private val jsonHourly = """
       {
           "data": [
               {
                   "wind_cdir": "SSE",
                   "rh": 95,
                   "pod": "n",
                   "timestamp_utc": "2020-05-25T13:00:00",
                   "pres": 1001.17,
                   "solar_rad": 0,
                   "ozone": 381.029,
                   "weather": {
                       "icon": "c04n",
                       "code": 804,
                       "description": "Overcast clouds"
                   },
                   "wind_gust_spd": 2.41328,
                   "timestamp_local": "2020-05-25T23:00:00",
                   "snow_depth": 0,
                   "clouds": 100,
                   "ts": 1590411600,
                   "wind_spd": 2.01829,
                   "pop": 25,
                   "wind_cdir_full": "south-southeast",
                   "slp": 1007.18,
                   "dni": 0,
                   "dewpt": 9.2,
                   "snow": 0,
                   "uv": 0,
                   "wind_dir": 167,
                   "clouds_hi": 0,
                   "precip": 0.3125,
                   "vis": 21.0413,
                   "dhi": 0,
                   "app_temp": 9.8,
                   "datetime": "2020-05-25:13",
                   "temp": 9.8,
                   "ghi": 0,
                   "clouds_mid": 100,
                   "clouds_low": 0
               },
               {
                   "wind_cdir": "SSE",
                   "rh": 96,
                   "pod": "n",
                   "timestamp_utc": "2020-05-25T14:00:00",
                   "pres": 1001.54,
                   "solar_rad": 0,
                   "ozone": 379.796,
                   "weather": {
                       "icon": "c03n",
                       "code": 803,
                       "description": "Broken clouds"
                   },
                   "wind_gust_spd": 2.80016,
                   "timestamp_local": "2020-05-26T00:00:00",
                   "snow_depth": 0,
                   "clouds": 52,
                   "ts": 1590415200,
                   "wind_spd": 2.28807,
                   "pop": 15,
                   "wind_cdir_full": "south-southeast",
                   "slp": 1007.44,
                   "dni": 0,
                   "dewpt": 8.7,
                   "snow": 0,
                   "uv": 0,
                   "wind_dir": 156,
                   "clouds_hi": 0,
                   "precip": 0.0625,
                   "vis": 24.1351,
                   "dhi": 0,
                   "app_temp": 9.5,
                   "datetime": "2020-05-25:14",
                   "temp": 9.5,
                   "ghi": 0,
                   "clouds_mid": 52,
                   "clouds_low": 0
               },
               {
                   "wind_cdir": "SSE",
                   "rh": 96,
                   "pod": "n",
                   "timestamp_utc": "2020-05-25T15:00:00",
                   "pres": 1001.21,
                   "solar_rad": 0,
                   "ozone": 379.474,
                   "weather": {
                       "icon": "c02n",
                       "code": 802,
                       "description": "Scattered clouds"
                   },
                   "wind_gust_spd": 3.00516,
                   "timestamp_local": "2020-05-26T01:00:00",
                   "snow_depth": 0,
                   "clouds": 35,
                   "ts": 1590418800,
                   "wind_spd": 2.37877,
                   "pop": 0,
                   "wind_cdir_full": "south-southeast",
                   "slp": 1007.19,
                   "dni": 0,
                   "dewpt": 8.6,
                   "snow": 0,
                   "uv": 0,
                   "wind_dir": 150,
                   "clouds_hi": 0,
                   "precip": 0,
                   "vis": 24.1348,
                   "dhi": 0,
                   "app_temp": 9.2,
                   "datetime": "2020-05-25:15",
                   "temp": 9.2,
                   "ghi": 0,
                   "clouds_mid": 34,
                   "clouds_low": 1
               },
               {
                   "wind_cdir": "SSE",
                   "rh": 97,
                   "pod": "n",
                   "timestamp_utc": "2020-05-25T16:00:00",
                   "pres": 1000.97,
                   "solar_rad": 0,
                   "ozone": 378.244,
                   "weather": {
                       "icon": "c02n",
                       "code": 802,
                       "description": "Scattered clouds"
                   },
                   "wind_gust_spd": 2.21842,
                   "timestamp_local": "2020-05-26T02:00:00",
                   "snow_depth": 0,
                   "clouds": 27,
                   "ts": 1590422400,
                   "wind_spd": 1.70942,
                   "pop": 0,
                   "wind_cdir_full": "south-southeast",
                   "slp": 1006.9,
                   "dni": 0,
                   "dewpt": 8.3,
                   "snow": 0,
                   "uv": 0,
                   "wind_dir": 166,
                   "clouds_hi": 0,
                   "precip": 0,
                   "vis": 13.2114,
                   "dhi": 0,
                   "app_temp": 8.8,
                   "datetime": "2020-05-25:16",
                   "temp": 8.8,
                   "ghi": 0,
                   "clouds_mid": 26,
                   "clouds_low": 2
               },
               {
                   "wind_cdir": "S",
                   "rh": 97,
                   "pod": "n",
                   "timestamp_utc": "2020-05-25T17:00:00",
                   "pres": 1000.47,
                   "solar_rad": 0,
                   "ozone": 377.616,
                   "weather": {
                       "icon": "c02n",
                       "code": 802,
                       "description": "Scattered clouds"
                   },
                   "wind_gust_spd": 1.60746,
                   "timestamp_local": "2020-05-26T03:00:00",
                   "snow_depth": 0,
                   "clouds": 24,
                   "ts": 1590426000,
                   "wind_spd": 1.20853,
                   "pop": 0,
                   "wind_cdir_full": "south",
                   "slp": 1006.18,
                   "dni": 0,
                   "dewpt": 8.3,
                   "snow": 0,
                   "uv": 0,
                   "wind_dir": 172,
                   "clouds_hi": 0,
                   "precip": 0,
                   "vis": 14.3383,
                   "dhi": 0,
                   "app_temp": 8.7,
                   "datetime": "2020-05-25:17",
                   "temp": 8.7,
                   "ghi": 0,
                   "clouds_mid": 21,
                   "clouds_low": 4
               },
               {
                   "wind_cdir": "SSE",
                   "rh": 97,
                   "pod": "n",
                   "timestamp_utc": "2020-05-25T18:00:00",
                   "pres": 1000.29,
                   "solar_rad": 0,
                   "ozone": 375.639,
                   "weather": {
                       "icon": "c02n",
                       "code": 802,
                       "description": "Scattered clouds"
                   },
                   "wind_gust_spd": 1.21371,
                   "timestamp_local": "2020-05-26T04:00:00",
                   "snow_depth": 0,
                   "clouds": 24,
                   "ts": 1590429600,
                   "wind_spd": 0.871516,
                   "pop": 0,
                   "wind_cdir_full": "south-southeast",
                   "slp": 1005.86,
                   "dni": 0,
                   "dewpt": 8.1,
                   "snow": 0,
                   "uv": 0,
                   "wind_dir": 156,
                   "clouds_hi": 0,
                   "precip": 0,
                   "vis": 19.7419,
                   "dhi": 0,
                   "app_temp": 8.5,
                   "datetime": "2020-05-25:18",
                   "temp": 8.5,
                   "ghi": 0,
                   "clouds_mid": 18,
                   "clouds_low": 6
               },
               {
                   "wind_cdir": "SSE",
                   "rh": 97,
                   "pod": "n",
                   "timestamp_utc": "2020-05-25T19:00:00",
                   "pres": 1000.27,
                   "solar_rad": 0,
                   "ozone": 373.605,
                   "weather": {
                       "icon": "c02n",
                       "code": 802,
                       "description": "Scattered clouds"
                   },
                   "wind_gust_spd": 1.41278,
                   "timestamp_local": "2020-05-26T05:00:00",
                   "snow_depth": 0,
                   "clouds": 30,
                   "ts": 1590433200,
                   "wind_spd": 1.0094,
                   "pop": 0,
                   "wind_cdir_full": "south-southeast",
                   "slp": 1005.82,
                   "dni": 0,
                   "dewpt": 8,
                   "snow": 0,
                   "uv": 0,
                   "wind_dir": 151,
                   "clouds_hi": 0,
                   "precip": 0,
                   "vis": 14.9973,
                   "dhi": 0,
                   "app_temp": 8.4,
                   "datetime": "2020-05-25:19",
                   "temp": 8.4,
                   "ghi": 0,
                   "clouds_mid": 0,
                   "clouds_low": 30
               },
               {
                   "wind_cdir": "SSE",
                   "rh": 97,
                   "pod": "d",
                   "timestamp_utc": "2020-05-25T20:00:00",
                   "pres": 1000.4,
                   "solar_rad": 19.2139,
                   "ozone": 374.958,
                   "weather": {
                       "icon": "c02d",
                       "code": 802,
                       "description": "Scattered clouds"
                   },
                   "wind_gust_spd": 2.01131,
                   "timestamp_local": "2020-05-26T06:00:00",
                   "snow_depth": 0,
                   "clouds": 32,
                   "ts": 1590436800,
                   "wind_spd": 1.53279,
                   "pop": 0,
                   "wind_cdir_full": "south-southeast",
                   "slp": 1006,
                   "dni": 153.15,
                   "dewpt": 8,
                   "snow": 0,
                   "uv": 1.5593,
                   "wind_dir": 160,
                   "clouds_hi": 0,
                   "precip": 0,
                   "vis": 18.4651,
                   "dhi": 21.58,
                   "app_temp": 8.5,
                   "datetime": "2020-05-25:20",
                   "temp": 8.5,
                   "ghi": 19.58,
                   "clouds_mid": 0,
                   "clouds_low": 32
               },
               {
                   "wind_cdir": "S",
                   "rh": 96,
                   "pod": "d",
                   "timestamp_utc": "2020-05-25T21:00:00",
                   "pres": 1000.42,
                   "solar_rad": 161.585,
                   "ozone": 375.426,
                   "weather": {
                       "icon": "c02d",
                       "code": 802,
                       "description": "Scattered clouds"
                   },
                   "wind_gust_spd": 2.24515,
                   "timestamp_local": "2020-05-26T07:00:00",
                   "snow_depth": 0,
                   "clouds": 37,
                   "ts": 1590440400,
                   "wind_spd": 1.6063,
                   "pop": 0,
                   "wind_cdir_full": "south",
                   "slp": 1006.21,
                   "dni": 527.52,
                   "dewpt": 8.7,
                   "snow": 0,
                   "uv": 1.58302,
                   "wind_dir": 173,
                   "clouds_hi": 0,
                   "precip": 0,
                   "vis": 13.5087,
                   "dhi": 58.94,
                   "app_temp": 9.4,
                   "datetime": "2020-05-25:21",
                   "temp": 9.4,
                   "ghi": 166.69,
                   "clouds_mid": 11,
                   "clouds_low": 31
               },
               {
                   "wind_cdir": "S",
                   "rh": 94,
                   "pod": "d",
                   "timestamp_utc": "2020-05-25T22:00:00",
                   "pres": 1000.76,
                   "solar_rad": 337.603,
                   "ozone": 374.649,
                   "weather": {
                       "icon": "c02d",
                       "code": 802,
                       "description": "Scattered clouds"
                   },
                   "wind_gust_spd": 3.65517,
                   "timestamp_local": "2020-05-26T08:00:00",
                   "snow_depth": 0,
                   "clouds": 39,
                   "ts": 1590444000,
                   "wind_spd": 2.15798,
                   "pop": 0,
                   "wind_cdir_full": "south",
                   "slp": 1006.05,
                   "dni": 695.89,
                   "dewpt": 9.4,
                   "snow": 0,
                   "uv": 1.96994,
                   "wind_dir": 191,
                   "clouds_hi": 0,
                   "precip": 0,
                   "vis": 24.135,
                   "dhi": 81.34,
                   "app_temp": 10.3,
                   "datetime": "2020-05-25:22",
                   "temp": 10.3,
                   "ghi": 350.44,
                   "clouds_mid": 12,
                   "clouds_low": 32
               },
               {
                   "wind_cdir": "S",
                   "rh": 93,
                   "pod": "d",
                   "timestamp_utc": "2020-05-25T23:00:00",
                   "pres": 1000.32,
                   "solar_rad": 507.26,
                   "ozone": 372.666,
                   "weather": {
                       "icon": "c03d",
                       "code": 803,
                       "description": "Broken clouds"
                   },
                   "wind_gust_spd": 5.31978,
                   "timestamp_local": "2020-05-26T09:00:00",
                   "snow_depth": 0,
                   "clouds": 44,
                   "ts": 1590447600,
                   "wind_spd": 3.72072,
                   "pop": 0,
                   "wind_cdir_full": "south",
                   "slp": 1005.68,
                   "dni": 792.7,
                   "dewpt": 9.6,
                   "snow": 0,
                   "uv": 2.70514,
                   "wind_dir": 172,
                   "clouds_hi": 0,
                   "precip": 0,
                   "vis": 24.135,
                   "dhi": 97.06,
                   "app_temp": 10.7,
                   "datetime": "2020-05-25:23",
                   "temp": 10.7,
                   "ghi": 536.9,
                   "clouds_mid": 9,
                   "clouds_low": 38
               },
               {
                   "wind_cdir": "S",
                   "rh": 90,
                   "pod": "d",
                   "timestamp_utc": "2020-05-26T00:00:00",
                   "pres": 1000.11,
                   "solar_rad": 647.576,
                   "ozone": 371.646,
                   "weather": {
                       "icon": "c03d",
                       "code": 803,
                       "description": "Broken clouds"
                   },
                   "wind_gust_spd": 5.00388,
                   "timestamp_local": "2020-05-26T10:00:00",
                   "snow_depth": 0,
                   "clouds": 51,
                   "ts": 1590451200,
                   "wind_spd": 3.71788,
                   "pop": 0,
                   "wind_cdir_full": "south",
                   "slp": 1005.32,
                   "dni": 852.99,
                   "dewpt": 9.5,
                   "snow": 0,
                   "uv": 3.62375,
                   "wind_dir": 170,
                   "clouds_hi": 9,
                   "precip": 0,
                   "vis": 19.8132,
                   "dhi": 108.29,
                   "app_temp": 11.2,
                   "datetime": "2020-05-26:00",
                   "temp": 11.2,
                   "ghi": 705.48,
                   "clouds_mid": 8,
                   "clouds_low": 44
               },
               {
                   "wind_cdir": "S",
                   "rh": 82,
                   "pod": "d",
                   "timestamp_utc": "2020-05-26T01:00:00",
                   "pres": 999.73,
                   "solar_rad": 288.961,
                   "ozone": 373.01,
                   "weather": {
                       "icon": "c04d",
                       "code": 804,
                       "description": "Overcast clouds"
                   },
                   "wind_gust_spd": 5.23023,
                   "timestamp_local": "2020-05-26T11:00:00",
                   "snow_depth": 0,
                   "clouds": 94,
                   "ts": 1590454800,
                   "wind_spd": 4.01445,
                   "pop": 15,
                   "wind_cdir_full": "south",
                   "slp": 1005.09,
                   "dni": 890.92,
                   "dewpt": 9.2,
                   "snow": 0,
                   "uv": 2.61586,
                   "wind_dir": 174,
                   "clouds_hi": 78,
                   "precip": 0.0625,
                   "vis": 19.8112,
                   "dhi": 116.02,
                   "app_temp": 12.4,
                   "datetime": "2020-05-26:01",
                   "temp": 12.4,
                   "ghi": 840.8,
                   "clouds_mid": 69,
                   "clouds_low": 71
               },
               {
                   "wind_cdir": "SSE",
                   "rh": 79,
                   "pod": "d",
                   "timestamp_utc": "2020-05-26T02:00:00",
                   "pres": 999.181,
                   "solar_rad": 301.349,
                   "ozone": 377.322,
                   "weather": {
                       "icon": "c04d",
                       "code": 804,
                       "description": "Overcast clouds"
                   },
                   "wind_gust_spd": 5.31499,
                   "timestamp_local": "2020-05-26T12:00:00",
                   "snow_depth": 0,
                   "clouds": 97,
                   "ts": 1590458400,
                   "wind_spd": 4.10188,
                   "pop": 10,
                   "wind_cdir_full": "south-southeast",
                   "slp": 1004.91,
                   "dni": 912.49,
                   "dewpt": 9.4,
                   "snow": 0,
                   "uv": 2.95283,
                   "wind_dir": 166,
                   "clouds_hi": 89,
                   "precip": 0.125,
                   "vis": 19.7732,
                   "dhi": 120.68,
                   "app_temp": 13.2,
                   "datetime": "2020-05-26:02",
                   "temp": 13.2,
                   "ghi": 930.71,
                   "clouds_mid": 84,
                   "clouds_low": 49
               },
               {
                   "wind_cdir": "SSE",
                   "rh": 72,
                   "pod": "d",
                   "timestamp_utc": "2020-05-26T03:00:00",
                   "pres": 998.695,
                   "solar_rad": 613.064,
                   "ozone": 374.232,
                   "weather": {
                       "icon": "c04d",
                       "code": 804,
                       "description": "Overcast clouds"
                   },
                   "wind_gust_spd": 6.3147,
                   "timestamp_local": "2020-05-26T13:00:00",
                   "snow_depth": 0,
                   "clouds": 81,
                   "ts": 1590462000,
                   "wind_spd": 5.18557,
                   "pop": 10,
                   "wind_cdir_full": "south-southeast",
                   "slp": 1004.7,
                   "dni": 920.64,
                   "dewpt": 9.1,
                   "snow": 0,
                   "uv": 4.23825,
                   "wind_dir": 164,
                   "clouds_hi": 60,
                   "precip": 0.125,
                   "vis": 12.4073,
                   "dhi": 122.5,
                   "app_temp": 14.3,
                   "datetime": "2020-05-26:03",
                   "temp": 14.3,
                   "ghi": 967.53,
                   "clouds_mid": 73,
                   "clouds_low": 43
               },
               {
                   "wind_cdir": "SSE",
                   "rh": 70,
                   "pod": "d",
                   "timestamp_utc": "2020-05-26T04:00:00",
                   "pres": 998.003,
                   "solar_rad": 736.661,
                   "ozone": 372.922,
                   "weather": {
                       "icon": "c03d",
                       "code": 803,
                       "description": "Broken clouds"
                   },
                   "wind_gust_spd": 6.30718,
                   "timestamp_local": "2020-05-26T14:00:00",
                   "snow_depth": 0,
                   "clouds": 70,
                   "ts": 1590465600,
                   "wind_spd": 5.09439,
                   "pop": 10,
                   "wind_cdir_full": "south-southeast",
                   "slp": 1004.26,
                   "dni": 916.4,
                   "dewpt": 8.8,
                   "snow": 0,
                   "uv": 4.78256,
                   "wind_dir": 157,
                   "clouds_hi": 45,
                   "precip": 0.125,
                   "vis": 19.7984,
                   "dhi": 121.55,
                   "app_temp": 14.4,
                   "datetime": "2020-05-26:04",
                   "temp": 14.4,
                   "ghi": 948.14,
                   "clouds_mid": 55,
                   "clouds_low": 41
               },
               {
                   "wind_cdir": "SSE",
                   "rh": 68,
                   "pod": "d",
                   "timestamp_utc": "2020-05-26T05:00:00",
                   "pres": 996.984,
                   "solar_rad": 714.567,
                   "ozone": 372.777,
                   "weather": {
                       "icon": "c03d",
                       "code": 803,
                       "description": "Broken clouds"
                   },
                   "wind_gust_spd": 5.40276,
                   "timestamp_local": "2020-05-26T15:00:00",
                   "snow_depth": 0,
                   "clouds": 66,
                   "ts": 1590469200,
                   "wind_spd": 4.2711,
                   "pop": 15,
                   "wind_cdir_full": "south-southeast",
                   "slp": 1003.51,
                   "dni": 899.23,
                   "dewpt": 8.7,
                   "snow": 0,
                   "uv": 4.34224,
                   "wind_dir": 153,
                   "clouds_hi": 36,
                   "precip": 0.0625,
                   "vis": 24.135,
                   "dhi": 117.79,
                   "app_temp": 14.7,
                   "datetime": "2020-05-26:05",
                   "temp": 14.7,
                   "ghi": 874.2,
                   "clouds_mid": 44,
                   "clouds_low": 43
               },
               {
                   "wind_cdir": "SSE",
                   "rh": 70,
                   "pod": "d",
                   "timestamp_utc": "2020-05-26T06:00:00",
                   "pres": 997.124,
                   "solar_rad": 621.644,
                   "ozone": 369.734,
                   "weather": {
                       "icon": "c03d",
                       "code": 803,
                       "description": "Broken clouds"
                   },
                   "wind_gust_spd": 4.90099,
                   "timestamp_local": "2020-05-26T16:00:00",
                   "snow_depth": 0,
                   "clouds": 65,
                   "ts": 1590472800,
                   "wind_spd": 3.22586,
                   "pop": 0,
                   "wind_cdir_full": "south-southeast",
                   "slp": 1003.05,
                   "dni": 866.89,
                   "dewpt": 8.1,
                   "snow": 0,
                   "uv": 3.40881,
                   "wind_dir": 149,
                   "clouds_hi": 30,
                   "precip": 0,
                   "vis": 24.135,
                   "dhi": 111.06,
                   "app_temp": 13.6,
                   "datetime": "2020-05-26:06",
                   "temp": 13.6,
                   "ghi": 752.02,
                   "clouds_mid": 36,
                   "clouds_low": 46
               },
               {
                   "wind_cdir": "SSE",
                   "rh": 73,
                   "pod": "d",
                   "timestamp_utc": "2020-05-26T07:00:00",
                   "pres": 997.003,
                   "solar_rad": 148.072,
                   "ozone": 366.524,
                   "weather": {
                       "icon": "c04d",
                       "code": 804,
                       "description": "Overcast clouds"
                   },
                   "wind_gust_spd": 3.60149,
                   "timestamp_local": "2020-05-26T17:00:00",
                   "snow_depth": 0,
                   "clouds": 100,
                   "ts": 1590476400,
                   "wind_spd": 2.32872,
                   "pop": 0,
                   "wind_cdir_full": "south-southeast",
                   "slp": 1002.86,
                   "dni": 814.42,
                   "dewpt": 7.7,
                   "snow": 0,
                   "uv": 1.35926,
                   "wind_dir": 157,
                   "clouds_hi": 0,
                   "precip": 0,
                   "vis": 24.135,
                   "dhi": 100.98,
                   "app_temp": 12.6,
                   "datetime": "2020-05-26:07",
                   "temp": 12.6,
                   "ghi": 592.29,
                   "clouds_mid": 0,
                   "clouds_low": 100
               },
               {
                   "wind_cdir": "S",
                   "rh": 69,
                   "pod": "d",
                   "timestamp_utc": "2020-05-26T08:00:00",
                   "pres": 996.893,
                   "solar_rad": 112.726,
                   "ozone": 366.685,
                   "weather": {
                       "icon": "c04d",
                       "code": 804,
                       "description": "Overcast clouds"
                   },
                   "wind_gust_spd": 2.02183,
                   "timestamp_local": "2020-05-26T18:00:00",
                   "snow_depth": 0,
                   "clouds": 99,
                   "ts": 1590480000,
                   "wind_spd": 1.44463,
                   "pop": 0,
                   "wind_cdir_full": "south",
                   "slp": 1002.73,
                   "dni": 731.33,
                   "dewpt": 8.3,
                   "snow": 0,
                   "uv": 0.954711,
                   "wind_dir": 187,
                   "clouds_hi": 0,
                   "precip": 0,
                   "vis": 24.1351,
                   "dhi": 86.82,
                   "app_temp": 13.9,
                   "datetime": "2020-05-26:08",
                   "temp": 13.9,
                   "ghi": 409.62,
                   "clouds_mid": 0,
                   "clouds_low": 99
               },
               {
                   "wind_cdir": "ESE",
                   "rh": 72,
                   "pod": "d",
                   "timestamp_utc": "2020-05-26T09:00:00",
                   "pres": 996.948,
                   "solar_rad": 61.2888,
                   "ozone": 367.222,
                   "weather": {
                       "icon": "c04d",
                       "code": 804,
                       "description": "Overcast clouds"
                   },
                   "wind_gust_spd": 1.80977,
                   "timestamp_local": "2020-05-26T19:00:00",
                   "snow_depth": 0,
                   "clouds": 99,
                   "ts": 1590483600,
                   "wind_spd": 1.16508,
                   "pop": 0,
                   "wind_cdir_full": "east-southeast",
                   "slp": 1002.73,
                   "dni": 592.32,
                   "dewpt": 8.3,
                   "snow": 0,
                   "uv": 0.715375,
                   "wind_dir": 120,
                   "clouds_hi": 12,
                   "precip": 0,
                   "vis": 24.1351,
                   "dhi": 66.95,
                   "app_temp": 13.2,
                   "datetime": "2020-05-26:09",
                   "temp": 13.2,
                   "ghi": 222.71,
                   "clouds_mid": 0,
                   "clouds_low": 97
               },
               {
                   "wind_cdir": "SE",
                   "rh": 72,
                   "pod": "d",
                   "timestamp_utc": "2020-05-26T10:00:00",
                   "pres": 997.089,
                   "solar_rad": 16.0191,
                   "ozone": 370.758,
                   "weather": {
                       "icon": "c04d",
                       "code": 804,
                       "description": "Overcast clouds"
                   },
                   "wind_gust_spd": 3.42199,
                   "timestamp_local": "2020-05-26T20:00:00",
                   "snow_depth": 0,
                   "clouds": 99,
                   "ts": 1590487200,
                   "wind_spd": 3.0228,
                   "pop": 0,
                   "wind_cdir_full": "southeast",
                   "slp": 1003.03,
                   "dni": 313.98,
                   "dewpt": 7.2,
                   "snow": 0,
                   "uv": 0.6398,
                   "wind_dir": 141,
                   "clouds_hi": 34,
                   "precip": 0,
                   "vis": 24.1348,
                   "dhi": 36.38,
                   "app_temp": 12.1,
                   "datetime": "2020-05-26:10",
                   "temp": 12.1,
                   "ghi": 58.21,
                   "clouds_mid": 0,
                   "clouds_low": 98
               },
               {
                   "wind_cdir": "SE",
                   "rh": 76,
                   "pod": "n",
                   "timestamp_utc": "2020-05-26T11:00:00",
                   "pres": 997.344,
                   "solar_rad": 0,
                   "ozone": 370.844,
                   "weather": {
                       "icon": "c04n",
                       "code": 804,
                       "description": "Overcast clouds"
                   },
                   "wind_gust_spd": 3.20626,
                   "timestamp_local": "2020-05-26T21:00:00",
                   "snow_depth": 0,
                   "clouds": 100,
                   "ts": 1590490800,
                   "wind_spd": 2.64325,
                   "pop": 0,
                   "wind_cdir_full": "southeast",
                   "slp": 1003.42,
                   "dni": 0,
                   "dewpt": 6.7,
                   "snow": 0,
                   "uv": 0,
                   "wind_dir": 145,
                   "clouds_hi": 47,
                   "precip": 0,
                   "vis": 24.135,
                   "dhi": 0,
                   "app_temp": 10.7,
                   "datetime": "2020-05-26:11",
                   "temp": 10.7,
                   "ghi": 0,
                   "clouds_mid": 0,
                   "clouds_low": 87
               },
               {
                   "wind_cdir": "SE",
                   "rh": 75,
                   "pod": "n",
                   "timestamp_utc": "2020-05-26T12:00:00",
                   "pres": 997.728,
                   "solar_rad": 0,
                   "ozone": 371.188,
                   "weather": {
                       "icon": "c04n",
                       "code": 804,
                       "description": "Overcast clouds"
                   },
                   "wind_gust_spd": 2.10254,
                   "timestamp_local": "2020-05-26T22:00:00",
                   "snow_depth": 0,
                   "clouds": 99,
                   "ts": 1590494400,
                   "wind_spd": 1.65033,
                   "pop": 0,
                   "wind_cdir_full": "southeast",
                   "slp": 1003.73,
                   "dni": 0,
                   "dewpt": 6.7,
                   "snow": 0,
                   "uv": 0,
                   "wind_dir": 140,
                   "clouds_hi": 41,
                   "precip": 0,
                   "vis": 24.1354,
                   "dhi": 0,
                   "app_temp": 10.9,
                   "datetime": "2020-05-26:12",
                   "temp": 10.9,
                   "ghi": 0,
                   "clouds_mid": 0,
                   "clouds_low": 88
               }
           ],
           "city_name": "Vladivostok",
           "lon": "131.87353",
           "timezone": "Asia/Vladivostok",
           "lat": "43.10562",
           "country_code": "RU",
           "state_code": "59"
       }
    """.trimIndent()

    private val jsonDaily = """
      {
          "data": [
              {
                  "moonrise_ts": 1590355258,
                  "wind_cdir": "Ю",
                  "rh": 75,
                  "pres": 1000.72,
                  "high_temp": 16.3,
                  "sunset_ts": 1590402911,
                  "ozone": 382.684,
                  "moon_phase": 0.0799868,
                  "wind_gust_spd": 11.9441,
                  "snow_depth": 0,
                  "clouds": 25,
                  "ts": 1590328860,
                  "sunrise_ts": 1590349155,
                  "app_min_temp": 9.8,
                  "wind_spd": 4.81278,
                  "pop": 65,
                  "wind_cdir_full": "Южный",
                  "slp": 1006.36,
                  "moon_phase_lunation": 0.08,
                  "valid_date": "2020-05-25",
                  "app_max_temp": 16.3,
                  "vis": 22.5512,
                  "dewpt": 9,
                  "snow": 0,
                  "uv": 0,
                  "weather": {
                      "icon": "c02d",
                      "code": 802,
                      "description": "Местами облачно"
                  },
                  "wind_dir": 180,
                  "max_dhi": null,
                  "clouds_hi": 0,
                  "precip": 1.75,
                  "low_temp": 8.4,
                  "max_temp": 16.7,
                  "moonset_ts": 1590411842,
                  "datetime": "2020-05-25",
                  "temp": 13.8,
                  "min_temp": 9.5,
                  "clouds_mid": 9,
                  "clouds_low": 16
              },
              {
                  "moonrise_ts": 1590444731,
                  "wind_cdir": "ЮЮВ",
                  "rh": 84,
                  "pres": 999.037,
                  "high_temp": 14.7,
                  "sunset_ts": 1590489365,
                  "ozone": 373.258,
                  "moon_phase": 0.148584,
                  "wind_gust_spd": 6.3147,
                  "snow_depth": 0,
                  "clouds": 65,
                  "ts": 1590415260,
                  "sunrise_ts": 1590435513,
                  "app_min_temp": 8.4,
                  "wind_spd": 2.55035,
                  "pop": 35,
                  "wind_cdir_full": "Юго-Юго-Восточный",
                  "slp": 1004.84,
                  "moon_phase_lunation": 0.11,
                  "valid_date": "2020-05-26",
                  "app_max_temp": 14.7,
                  "vis": 20.8175,
                  "dewpt": 8.3,
                  "snow": 0,
                  "uv": 4.78256,
                  "weather": {
                      "icon": "c03d",
                      "code": 803,
                      "description": "Облачно с прояснениями"
                  },
                  "wind_dir": 158,
                  "max_dhi": null,
                  "clouds_hi": 24,
                  "precip": 0.5625,
                  "low_temp": 8.2,
                  "max_temp": 15.3,
                  "moonset_ts": 1590501471,
                  "datetime": "2020-05-26",
                  "temp": 11.2,
                  "min_temp": 8.1,
                  "clouds_mid": 23,
                  "clouds_low": 48
              },
              {
                  "moonrise_ts": 1590534681,
                  "wind_cdir": "ЗСЗ",
                  "rh": 83,
                  "pres": 997.127,
                  "high_temp": 16.4,
                  "sunset_ts": 1590575818,
                  "ozone": 384.184,
                  "moon_phase": 0.235229,
                  "wind_gust_spd": 6.54171,
                  "snow_depth": 0,
                  "clouds": 60,
                  "ts": 1590501660,
                  "sunrise_ts": 1590521873,
                  "app_min_temp": 8.2,
                  "wind_spd": 1.8699,
                  "pop": 90,
                  "wind_cdir_full": "Западный-Северо-Западный",
                  "slp": 1002.82,
                  "moon_phase_lunation": 0.15,
                  "valid_date": "2020-05-27",
                  "app_max_temp": 16.4,
                  "vis": 19.7814,
                  "dewpt": 9.7,
                  "snow": 0,
                  "uv": 5.10956,
                  "weather": {
                      "icon": "r01d",
                      "code": 500,
                      "description": "Небольшой дождь"
                  },
                  "wind_dir": 301,
                  "max_dhi": null,
                  "clouds_hi": 55,
                  "precip": 7.1875,
                  "low_temp": 9.3,
                  "max_temp": 16.6,
                  "moonset_ts": 1590504300,
                  "datetime": "2020-05-27",
                  "temp": 12.5,
                  "min_temp": 8,
                  "clouds_mid": 39,
                  "clouds_low": 21
              },
              {
                  "moonrise_ts": 1590625017,
                  "wind_cdir": "ЮЗ",
                  "rh": 73,
                  "pres": 1000.56,
                  "high_temp": 21.6,
                  "sunset_ts": 1590662270,
                  "ozone": 373.047,
                  "moon_phase": 0.336453,
                  "wind_gust_spd": 4.42015,
                  "snow_depth": 0,
                  "clouds": 2,
                  "ts": 1590588060,
                  "sunrise_ts": 1590608235,
                  "app_min_temp": 9.3,
                  "wind_spd": 1.44228,
                  "pop": 15,
                  "wind_cdir_full": "Юго-Западный",
                  "slp": 1006.68,
                  "moon_phase_lunation": 0.18,
                  "valid_date": "2020-05-28",
                  "app_max_temp": 21.1,
                  "vis": 23.8239,
                  "dewpt": 9.6,
                  "snow": 0,
                  "uv": 9.6563,
                  "weather": {
                      "icon": "c02d",
                      "code": 801,
                      "description": "Преимущественно ясно"
                  },
                  "wind_dir": 231,
                  "max_dhi": null,
                  "clouds_hi": 1,
                  "precip": 0.4375,
                  "low_temp": 10.8,
                  "max_temp": 22,
                  "moonset_ts": 1590593131,
                  "datetime": "2020-05-28",
                  "temp": 15.1,
                  "min_temp": 9.2,
                  "clouds_mid": 0,
                  "clouds_low": 2
              },
              {
                  "moonrise_ts": 1590715605,
                  "wind_cdir": "ЮЗ",
                  "rh": 68,
                  "pres": 1005.7,
                  "high_temp": 21.1,
                  "sunset_ts": 1590748721,
                  "ozone": 371.727,
                  "moon_phase": 0.447794,
                  "wind_gust_spd": 6.0256,
                  "snow_depth": 0,
                  "clouds": 0,
                  "ts": 1590674460,
                  "sunrise_ts": 1590694599,
                  "app_min_temp": 10.8,
                  "wind_spd": 2.27953,
                  "pop": 0,
                  "wind_cdir_full": "Юго-Западный",
                  "slp": 1011.59,
                  "moon_phase_lunation": 0.22,
                  "valid_date": "2020-05-29",
                  "app_max_temp": 20.6,
                  "vis": 24.135,
                  "dewpt": 9.5,
                  "snow": 0,
                  "uv": 9.67922,
                  "weather": {
                      "icon": "c01d",
                      "code": 800,
                      "description": "Ясно"
                  },
                  "wind_dir": 225,
                  "max_dhi": null,
                  "clouds_hi": 0,
                  "precip": 0,
                  "low_temp": 10.2,
                  "max_temp": 21.7,
                  "moonset_ts": 1590681629,
                  "datetime": "2020-05-29",
                  "temp": 15.9,
                  "min_temp": 10.8,
                  "clouds_mid": 0,
                  "clouds_low": 0
              },
              {
                  "moonrise_ts": 1590802005,
                  "wind_cdir": "Ю",
                  "rh": 77,
                  "pres": 1008.46,
                  "high_temp": 17.1,
                  "sunset_ts": 1590835170,
                  "ozone": 364.668,
                  "moon_phase": 0.563817,
                  "wind_gust_spd": 8.80468,
                  "snow_depth": 0,
                  "clouds": 0,
                  "ts": 1590760860,
                  "sunrise_ts": 1590780965,
                  "app_min_temp": 10.2,
                  "wind_spd": 3.27652,
                  "pop": 0,
                  "wind_cdir_full": "Южный",
                  "slp": 1013.87,
                  "moon_phase_lunation": 0.25,
                  "valid_date": "2020-05-30",
                  "app_max_temp": 16.4,
                  "vis": 24.1349,
                  "dewpt": 8.6,
                  "snow": 0,
                  "uv": 9.71214,
                  "weather": {
                      "icon": "c01d",
                      "code": 800,
                      "description": "Ясно"
                  },
                  "wind_dir": 171,
                  "max_dhi": null,
                  "clouds_hi": 0,
                  "precip": 0,
                  "low_temp": 10.3,
                  "max_temp": 16.7,
                  "moonset_ts": 1590769887,
                  "datetime": "2020-05-30",
                  "temp": 12.7,
                  "min_temp": 10,
                  "clouds_mid": 0,
                  "clouds_low": 0
              },
              {
                  "moonrise_ts": 1590892723,
                  "wind_cdir": "Ю",
                  "rh": 91,
                  "pres": 1007.5,
                  "high_temp": 18.3,
                  "sunset_ts": 1590921619,
                  "ozone": 350.353,
                  "moon_phase": 0.678214,
                  "wind_gust_spd": 6.70278,
                  "snow_depth": 0,
                  "clouds": 78,
                  "ts": 1590847260,
                  "sunrise_ts": 1590867333,
                  "app_min_temp": 10.3,
                  "wind_spd": 3.38654,
                  "pop": 55,
                  "wind_cdir_full": "Южный",
                  "slp": 1013.06,
                  "moon_phase_lunation": 0.28,
                  "valid_date": "2020-05-31",
                  "app_max_temp": 17.1,
                  "vis": 20.0485,
                  "dewpt": 11.6,
                  "snow": 0,
                  "uv": 3.02401,
                  "weather": {
                      "icon": "c04d",
                      "code": 804,
                      "description": "Облачно"
                  },
                  "wind_dir": 170,
                  "max_dhi": null,
                  "clouds_hi": 72,
                  "precip": 1.3125,
                  "low_temp": 11.3,
                  "max_temp": 17.2,
                  "moonset_ts": 1590858004,
                  "datetime": "2020-05-31",
                  "temp": 13.1,
                  "min_temp": 10.1,
                  "clouds_mid": 19,
                  "clouds_low": 51
              },
              {
                  "moonrise_ts": 1590983499,
                  "wind_cdir": "ЮЮВ",
                  "rh": 86,
                  "pres": 1006.04,
                  "high_temp": 16.6,
                  "sunset_ts": 1591008065,
                  "ozone": 355.602,
                  "moon_phase": 0.784093,
                  "wind_gust_spd": 8.62774,
                  "snow_depth": 0,
                  "clouds": 16,
                  "ts": 1590933660,
                  "sunrise_ts": 1590953703,
                  "app_min_temp": 11.3,
                  "wind_spd": 3.30778,
                  "pop": 0,
                  "wind_cdir_full": "Юго-Юго-Восточный",
                  "slp": 1011.51,
                  "moon_phase_lunation": 0.32,
                  "valid_date": "2020-06-01",
                  "app_max_temp": 18.3,
                  "vis": 20.27,
                  "dewpt": 11.9,
                  "snow": 0,
                  "uv": 8.41208,
                  "weather": {
                      "icon": "c02d",
                      "code": 801,
                      "description": "Преимущественно ясно"
                  },
                  "wind_dir": 156,
                  "max_dhi": null,
                  "clouds_hi": 0,
                  "precip": 0,
                  "low_temp": 11.3,
                  "max_temp": 19.1,
                  "moonset_ts": 1590946075,
                  "datetime": "2020-06-01",
                  "temp": 14.4,
                  "min_temp": 10.8,
                  "clouds_mid": 0,
                  "clouds_low": 16
              },
              {
                  "moonrise_ts": 1591074318,
                  "wind_cdir": "ЮЮВ",
                  "rh": 87,
                  "pres": 1004.74,
                  "high_temp": 14.6,
                  "sunset_ts": 1591094511,
                  "ozone": 346.743,
                  "moon_phase": 0.874539,
                  "wind_gust_spd": 7.70466,
                  "snow_depth": 0,
                  "clouds": 55,
                  "ts": 1591020060,
                  "sunrise_ts": 1591040075,
                  "app_min_temp": 11.3,
                  "wind_spd": 3.704,
                  "pop": 35,
                  "wind_cdir_full": "Юго-Юго-Восточный",
                  "slp": 1009.97,
                  "moon_phase_lunation": 0.35,
                  "valid_date": "2020-06-02",
                  "app_max_temp": 16.6,
                  "vis": 20.8174,
                  "dewpt": 11.7,
                  "snow": 0,
                  "uv": 4.24981,
                  "weather": {
                      "icon": "c03d",
                      "code": 803,
                      "description": "Облачно с прояснениями"
                  },
                  "wind_dir": 162,
                  "max_dhi": null,
                  "clouds_hi": 33,
                  "precip": 0.5,
                  "low_temp": 12,
                  "max_temp": 17.4,
                  "moonset_ts": 1591034197,
                  "datetime": "2020-06-02",
                  "temp": 13.8,
                  "min_temp": 11.3,
                  "clouds_mid": 0,
                  "clouds_low": 25
              },
              {
                  "moonrise_ts": 1591165193,
                  "wind_cdir": "ЮЮВ",
                  "rh": 92,
                  "pres": 1003.7,
                  "high_temp": 17.3,
                  "sunset_ts": 1591180955,
                  "ozone": 331.12,
                  "moon_phase": 0.943372,
                  "wind_gust_spd": 10.5103,
                  "snow_depth": 0,
                  "clouds": 83,
                  "ts": 1591106460,
                  "sunrise_ts": 1591126449,
                  "app_min_temp": 12,
                  "wind_spd": 5.13502,
                  "pop": 30,
                  "wind_cdir_full": "Юго-Юго-Восточный",
                  "slp": 1008.1,
                  "moon_phase_lunation": 0.38,
                  "valid_date": "2020-06-03",
                  "app_max_temp": 14.6,
                  "vis": 16.3812,
                  "dewpt": 11.7,
                  "snow": 0,
                  "uv": 3.052,
                  "weather": {
                      "icon": "c04d",
                      "code": 804,
                      "description": "Облачно"
                  },
                  "wind_dir": 168,
                  "max_dhi": null,
                  "clouds_hi": 38,
                  "precip": 0.4375,
                  "low_temp": 11.2,
                  "max_temp": 15,
                  "moonset_ts": 1591122473,
                  "datetime": "2020-06-03",
                  "temp": 13,
                  "min_temp": 11.7,
                  "clouds_mid": 6,
                  "clouds_low": 77
              },
              {
                  "moonrise_ts": 1591256139,
                  "wind_cdir": "ЮЮВ",
                  "rh": 98,
                  "pres": 999.343,
                  "high_temp": 19.8,
                  "sunset_ts": 1591267398,
                  "ozone": 343.145,
                  "moon_phase": 0.985965,
                  "wind_gust_spd": 8.40506,
                  "snow_depth": 0,
                  "clouds": 100,
                  "ts": 1591192860,
                  "sunrise_ts": 1591212826,
                  "app_min_temp": 11.2,
                  "wind_spd": 3.27225,
                  "pop": 85,
                  "wind_cdir_full": "Юго-Юго-Восточный",
                  "slp": 1004.58,
                  "moon_phase_lunation": 0.42,
                  "valid_date": "2020-06-04",
                  "app_max_temp": 13.2,
                  "vis": 5.09565,
                  "dewpt": 11.9,
                  "snow": 0,
                  "uv": 1.77512,
                  "weather": {
                      "icon": "r01d",
                      "code": 500,
                      "description": "Небольшой дождь"
                  },
                  "wind_dir": 167,
                  "max_dhi": null,
                  "clouds_hi": 75,
                  "precip": 6.125,
                  "low_temp": 10.8,
                  "max_temp": 17.2,
                  "moonset_ts": 1591211011,
                  "datetime": "2020-06-04",
                  "temp": 12.2,
                  "min_temp": 10.9,
                  "clouds_mid": 75,
                  "clouds_low": 99
              },
              {
                  "moonrise_ts": 1591347128,
                  "wind_cdir": "ЮЮВ",
                  "rh": 77,
                  "pres": 999.158,
                  "high_temp": 17.7,
                  "sunset_ts": 1591353839,
                  "ozone": 388.515,
                  "moon_phase": 0.999893,
                  "wind_gust_spd": 7.54913,
                  "snow_depth": 0,
                  "clouds": 98,
                  "ts": 1591279260,
                  "sunrise_ts": 1591299204,
                  "app_min_temp": 13.8,
                  "wind_spd": 3.56674,
                  "pop": 65,
                  "wind_cdir_full": "Юго-Юго-Восточный",
                  "slp": 1005.06,
                  "moon_phase_lunation": 0.45,
                  "valid_date": "2020-06-05",
                  "app_max_temp": 17.3,
                  "vis": 24.1351,
                  "dewpt": 11.3,
                  "snow": 0,
                  "uv": 1.83555,
                  "weather": {
                      "icon": "c04d",
                      "code": 804,
                      "description": "Облачно"
                  },
                  "wind_dir": 155,
                  "max_dhi": null,
                  "clouds_hi": 78,
                  "precip": 1.75,
                  "low_temp": 12.3,
                  "max_temp": 19.1,
                  "moonset_ts": 1591299919,
                  "datetime": "2020-06-05",
                  "temp": 15.6,
                  "min_temp": 11.3,
                  "clouds_mid": 53,
                  "clouds_low": 10
              },
              {
                  "moonrise_ts": 1591438063,
                  "wind_cdir": "ВЮВ",
                  "rh": 70,
                  "pres": 1002.43,
                  "high_temp": 16.9,
                  "sunset_ts": 1591440279,
                  "ozone": 393.311,
                  "moon_phase": 0.985234,
                  "wind_gust_spd": 10.3115,
                  "snow_depth": 0,
                  "clouds": 18,
                  "ts": 1591365660,
                  "sunrise_ts": 1591385585,
                  "app_min_temp": 10.8,
                  "wind_spd": 4.21518,
                  "pop": 0,
                  "wind_cdir_full": "Восточный-Юго-Восточный",
                  "slp": 1008.22,
                  "moon_phase_lunation": 0.49,
                  "valid_date": "2020-06-06",
                  "app_max_temp": 18.3,
                  "vis": 24.1349,
                  "dewpt": 8.7,
                  "snow": 0,
                  "uv": 4.5598,
                  "weather": {
                      "icon": "c02d",
                      "code": 801,
                      "description": "Преимущественно ясно"
                  },
                  "wind_dir": 112,
                  "max_dhi": null,
                  "clouds_hi": 14,
                  "precip": 0,
                  "low_temp": 15.2,
                  "max_temp": 22.4,
                  "moonset_ts": 1591389269,
                  "datetime": "2020-06-06",
                  "temp": 14.9,
                  "min_temp": 10.2,
                  "clouds_mid": 0,
                  "clouds_low": 4
              },
              {
                  "moonrise_ts": 1591528763,
                  "wind_cdir": "ЮЮВ",
                  "rh": 64,
                  "pres": 1003.71,
                  "high_temp": 23.9,
                  "sunset_ts": 1591526718,
                  "ozone": 356.483,
                  "moon_phase": 0.944432,
                  "wind_gust_spd": 6.53124,
                  "snow_depth": 0,
                  "clouds": 2,
                  "ts": 1591452060,
                  "sunrise_ts": 1591471967,
                  "app_min_temp": 16,
                  "wind_spd": 2.55345,
                  "pop": 0,
                  "wind_cdir_full": "Юго-Юго-Восточный",
                  "slp": 1009.59,
                  "moon_phase_lunation": 0.52,
                  "valid_date": "2020-06-07",
                  "app_max_temp": 18.2,
                  "vis": 24.1351,
                  "dewpt": 10.1,
                  "snow": 0,
                  "uv": 5.71332,
                  "weather": {
                      "icon": "c02d",
                      "code": 801,
                      "description": "Преимущественно ясно"
                  },
                  "wind_dir": 159,
                  "max_dhi": null,
                  "clouds_hi": 2,
                  "precip": 0,
                  "low_temp": 12.8,
                  "max_temp": 23.9,
                  "moonset_ts": 1591479054,
                  "datetime": "2020-06-07",
                  "temp": 17.5,
                  "min_temp": 12.8,
                  "clouds_mid": 0,
                  "clouds_low": 0
              },
              {
                  "moonrise_ts": 1591619025,
                  "wind_cdir": "ВЮВ",
                  "rh": 72,
                  "pres": 1001.31,
                  "high_temp": 18.1,
                  "sunset_ts": 1591613154,
                  "ozone": 338.684,
                  "moon_phase": 0.881768,
                  "wind_gust_spd": 6.32052,
                  "snow_depth": 0,
                  "clouds": 72,
                  "ts": 1591538460,
                  "sunrise_ts": 1591558352,
                  "app_min_temp": 12.3,
                  "wind_spd": 2.25738,
                  "pop": 0,
                  "wind_cdir_full": "Восточный-Юго-Восточный",
                  "slp": 1006.82,
                  "moon_phase_lunation": 0.55,
                  "valid_date": "2020-06-08",
                  "app_max_temp": 19.4,
                  "vis": 24.1349,
                  "dewpt": 10.7,
                  "snow": 0,
                  "uv": 2.81904,
                  "weather": {
                      "icon": "c04d",
                      "code": 804,
                      "description": "Облачно"
                  },
                  "wind_dir": 123,
                  "max_dhi": null,
                  "clouds_hi": 66,
                  "precip": 0,
                  "low_temp": 11.3,
                  "max_temp": 19.8,
                  "moonset_ts": 1591569163,
                  "datetime": "2020-06-08",
                  "temp": 16.1,
                  "min_temp": 11.3,
                  "clouds_mid": 20,
                  "clouds_low": 0
              },
              {
                  "moonrise_ts": 1591708716,
                  "wind_cdir": "ЮЮЗ",
                  "rh": 78,
                  "pres": 998.294,
                  "high_temp": 24,
                  "sunset_ts": 1591699590,
                  "ozone": 328.832,
                  "moon_phase": 0.802507,
                  "wind_gust_spd": 3.21037,
                  "snow_depth": 0,
                  "clouds": 86,
                  "ts": 1591624860,
                  "sunrise_ts": 1591644739,
                  "app_min_temp": 16.9,
                  "wind_spd": 1.6547,
                  "pop": 20,
                  "wind_cdir_full": "Юго-Юго-Западный",
                  "slp": 1004.19,
                  "moon_phase_lunation": 0.59,
                  "valid_date": "2020-06-09",
                  "app_max_temp": 17.7,
                  "vis": 19.5517,
                  "dewpt": 13.4,
                  "snow": 0,
                  "uv": 2.94488,
                  "weather": {
                      "icon": "c04d",
                      "code": 804,
                      "description": "Облачно"
                  },
                  "wind_dir": 201,
                  "max_dhi": null,
                  "clouds_hi": 86,
                  "precip": 0.75,
                  "low_temp": 13.6,
                  "max_temp": 24,
                  "moonset_ts": 1591659428,
                  "datetime": "2020-06-09",
                  "temp": 17.3,
                  "min_temp": 13.6,
                  "clouds_mid": 12,
                  "clouds_low": 0
              }
          ],
          "city_name": "Vladivostok",
          "lon": "131.87353",
          "timezone": "Asia/Vladivostok",
          "lat": "43.10562",
          "country_code": "RU",
          "state_code": "59"
      }
    """.trimIndent()

    private val jsonCurrent = """
     {
         "data": [
             {
                 "rh": 95,
                 "pod": "n",
                 "lon": 131.87353,
                 "pres": 1001.17,
                 "timezone": "Asia/Vladivostok",
                 "ob_time": "2020-05-25 12:50",
                 "country_code": "RU",
                 "clouds": 100,
                 "ts": 1590411042,
                 "solar_rad": 0,
                 "state_code": "59",
                 "city_name": "Vladivostok",
                 "wind_spd": 2.01829,
                 "last_ob_time": "2020-05-25T12:00:00",
                 "wind_cdir_full": "south-southeast",
                 "wind_cdir": "SSE",
                 "slp": 1007.18,
                 "vis": 21.0413,
                 "h_angle": -90,
                 "sunset": "10:40",
                 "dni": 0,
                 "dewpt": 9.2,
                 "snow": 0,
                 "uv": 0,
                 "precip": 0,
                 "wind_dir": 167,
                 "sunrise": "19:37",
                 "ghi": 0,
                 "dhi": 0,
                 "aqi": 70,
                 "lat": 43.10562,
                 "weather": {
                     "icon": "c02n",
                     "code": "802",
                     "description": "Scattered clouds"
                 },
                 "datetime": "2020-05-25:12",
                 "temp": 9.8,
                 "station": "UHWW",
                 "elev_angle": -12.48,
                 "app_temp": 9.8
             }
         ],
         "count": 1
     }
    """.trimIndent()

}