/*
 * Сreated by Igor Pokrovsky. 2020/4/29
 */

package com.nigtime.weatherapplication.common.testing

import com.google.gson.Gson
import com.nigtime.weatherapplication.net.json.JsonCurrentForecast
import com.nigtime.weatherapplication.net.json.JsonDailyForecast
import com.nigtime.weatherapplication.net.json.JsonHourlyForecast


object FakeJsonDataProvider {
    private val gson = lazy {
        Gson()
    }

    fun getHourlyForecast(): JsonHourlyForecast =
        gson.value.fromJson<JsonHourlyForecast>(jsonHourly, JsonHourlyForecast::class.java)

    fun getDailyForecast(): JsonDailyForecast =
        gson.value.fromJson<JsonDailyForecast>(jsonDaily, JsonDailyForecast::class.java)

    fun getCurrentForecast(): JsonCurrentForecast =
        gson.value.fromJson<JsonCurrentForecast>(jsonCurrent, JsonCurrentForecast::class.java)


    private val jsonHourly = """
        {
            "data": [
                {
                    "wind_cdir": "WSW",
                    "rh": 86,
                    "pod": "d",
                    "timestamp_utc": "2020-05-10T21:00:00",
                    "pres": 986.849,
                    "solar_rad": 133.597,
                    "ozone": 403.662,
                    "weather": {
                        "icon": "c02d",
                        "code": 801,
                        "description": "Few clouds"
                    },
                    "wind_gust_spd": 12.2081,
                    "timestamp_local": "2020-05-11T07:00:00",
                    "snow_depth": 0,
                    "clouds": 19,
                    "ts": 1589144400,
                    "wind_spd": 3.38787,
                    "pop": 0,
                    "wind_cdir_full": "west-southwest",
                    "slp": 993.271,
                    "dni": 481.44,
                    "dewpt": 6.5,
                    "snow": 0,
                    "uv": 1.76731,
                    "wind_dir": 255,
                    "clouds_hi": 0,
                    "precip": 0,
                    "vis": 24.1351,
                    "dhi": 53.63,
                    "app_temp": 8.6,
                    "datetime": "2020-05-10:21",
                    "temp": 8.6,
                    "ghi": 133.98,
                    "clouds_mid": 11,
                    "clouds_low": 10
                },
                {
                    "wind_cdir": "W",
                    "rh": 81,
                    "pod": "d",
                    "timestamp_utc": "2020-05-10T22:00:00",
                    "pres": 987.048,
                    "solar_rad": 313.101,
                    "ozone": 403.17,
                    "weather": {
                        "icon": "c02d",
                        "code": 802,
                        "description": "Scattered clouds"
                    },
                    "wind_gust_spd": 9.10069,
                    "timestamp_local": "2020-05-11T08:00:00",
                    "snow_depth": 0,
                    "clouds": 32,
                    "ts": 1589148000,
                    "wind_spd": 1.70261,
                    "pop": 0,
                    "wind_cdir_full": "west",
                    "slp": 993.138,
                    "dni": 676.75,
                    "dewpt": 7.1,
                    "snow": 0,
                    "uv": 1.95587,
                    "wind_dir": 264,
                    "clouds_hi": 0,
                    "precip": 0,
                    "vis": 24.1352,
                    "dhi": 78.39,
                    "app_temp": 10.3,
                    "datetime": "2020-05-10:22",
                    "temp": 10.3,
                    "ghi": 318.46,
                    "clouds_mid": 25,
                    "clouds_low": 8
                },
                {
                    "wind_cdir": "WSW",
                    "rh": 71,
                    "pod": "d",
                    "timestamp_utc": "2020-05-10T23:00:00",
                    "pres": 986.842,
                    "solar_rad": 499.977,
                    "ozone": 400.4,
                    "weather": {
                        "icon": "c02d",
                        "code": 802,
                        "description": "Scattered clouds"
                    },
                    "wind_gust_spd": 8.11328,
                    "timestamp_local": "2020-05-11T09:00:00",
                    "snow_depth": 0,
                    "clouds": 32,
                    "ts": 1589151600,
                    "wind_spd": 2.99012,
                    "pop": 0,
                    "wind_cdir_full": "west-southwest",
                    "slp": 993.079,
                    "dni": 783.65,
                    "dewpt": 7.5,
                    "snow": 0,
                    "uv": 2.8044,
                    "wind_dir": 250,
                    "clouds_hi": 0,
                    "precip": 0,
                    "vis": 24.1347,
                    "dhi": 95.24,
                    "app_temp": 12.7,
                    "datetime": "2020-05-10:23",
                    "temp": 12.7,
                    "ghi": 507.89,
                    "clouds_mid": 27,
                    "clouds_low": 6
                },
                {
                    "wind_cdir": "W",
                    "rh": 65,
                    "pod": "d",
                    "timestamp_utc": "2020-05-11T00:00:00",
                    "pres": 986.963,
                    "solar_rad": 673.688,
                    "ozone": 398.293,
                    "weather": {
                        "icon": "c02d",
                        "code": 802,
                        "description": "Scattered clouds"
                    },
                    "wind_gust_spd": 9.80458,
                    "timestamp_local": "2020-05-11T10:00:00",
                    "snow_depth": 0,
                    "clouds": 27,
                    "ts": 1589155200,
                    "wind_spd": 4.86108,
                    "pop": 15,
                    "wind_cdir_full": "west",
                    "slp": 993.207,
                    "dni": 848.61,
                    "dewpt": 7.5,
                    "snow": 0,
                    "uv": 4.24717,
                    "wind_dir": 272,
                    "clouds_hi": 0,
                    "precip": 0.1875,
                    "vis": 17.4069,
                    "dhi": 107.09,
                    "app_temp": 14.1,
                    "datetime": "2020-05-11:00",
                    "temp": 14.1,
                    "ghi": 679.63,
                    "clouds_mid": 22,
                    "clouds_low": 5
                },
                {
                    "wind_cdir": "WNW",
                    "rh": 63,
                    "pod": "d",
                    "timestamp_utc": "2020-05-11T01:00:00",
                    "pres": 987.47,
                    "solar_rad": 817.56,
                    "ozone": 396.989,
                    "weather": {
                        "icon": "c01d",
                        "code": 800,
                        "description": "Clear Sky"
                    },
                    "wind_gust_spd": 10.1344,
                    "timestamp_local": "2020-05-11T11:00:00",
                    "snow_depth": 0,
                    "clouds": 0,
                    "ts": 1589158800,
                    "wind_spd": 5.88765,
                    "pop": 30,
                    "wind_cdir_full": "west-northwest",
                    "slp": 993.618,
                    "dni": 888.99,
                    "dewpt": 7.5,
                    "snow": 0,
                    "uv": 7.01323,
                    "wind_dir": 292,
                    "clouds_hi": 0,
                    "precip": 0.4375,
                    "vis": 13.1066,
                    "dhi": 115.18,
                    "app_temp": 14.5,
                    "datetime": "2020-05-11:01",
                    "temp": 14.5,
                    "ghi": 817.56,
                    "clouds_mid": 0,
                    "clouds_low": 0
                },
                {
                    "wind_cdir": "WNW",
                    "rh": 56,
                    "pod": "d",
                    "timestamp_utc": "2020-05-11T02:00:00",
                    "pres": 987.827,
                    "solar_rad": 908.188,
                    "ozone": 399.241,
                    "weather": {
                        "icon": "c02d",
                        "code": 801,
                        "description": "Few clouds"
                    },
                    "wind_gust_spd": 11.4182,
                    "timestamp_local": "2020-05-11T12:00:00",
                    "snow_depth": 0,
                    "clouds": 14,
                    "ts": 1589162400,
                    "wind_spd": 6.88368,
                    "pop": 10,
                    "wind_cdir_full": "west-northwest",
                    "slp": 993.724,
                    "dni": 911.75,
                    "dewpt": 6.5,
                    "snow": 0,
                    "uv": 7.64496,
                    "wind_dir": 298,
                    "clouds_hi": 4,
                    "precip": 0.125,
                    "vis": 24.1351,
                    "dhi": 120.04,
                    "app_temp": 15.3,
                    "datetime": "2020-05-11:02",
                    "temp": 15.3,
                    "ghi": 909.04,
                    "clouds_mid": 11,
                    "clouds_low": 2
                },
                {
                    "wind_cdir": "WNW",
                    "rh": 46,
                    "pod": "d",
                    "timestamp_utc": "2020-05-11T03:00:00",
                    "pres": 987.978,
                    "solar_rad": 943.645,
                    "ozone": 399.958,
                    "weather": {
                        "icon": "c02d",
                        "code": 801,
                        "description": "Few clouds"
                    },
                    "wind_gust_spd": 10.9169,
                    "timestamp_local": "2020-05-11T13:00:00",
                    "snow_depth": 0,
                    "clouds": 19,
                    "ts": 1589166000,
                    "wind_spd": 6.05198,
                    "pop": 0,
                    "wind_cdir_full": "west-northwest",
                    "slp": 993.784,
                    "dni": 920.24,
                    "dewpt": 4.7,
                    "snow": 0,
                    "uv": 7.91822,
                    "wind_dir": 300,
                    "clouds_hi": 3,
                    "precip": 0,
                    "vis": 24.1351,
                    "dhi": 121.9,
                    "app_temp": 16.3,
                    "datetime": "2020-05-11:03",
                    "temp": 16.3,
                    "ghi": 946.15,
                    "clouds_mid": 8,
                    "clouds_low": 11
                },
                {
                    "wind_cdir": "NW",
                    "rh": 39,
                    "pod": "d",
                    "timestamp_utc": "2020-05-11T04:00:00",
                    "pres": 987.642,
                    "solar_rad": 924.021,
                    "ozone": 397.608,
                    "weather": {
                        "icon": "c02d",
                        "code": 801,
                        "description": "Few clouds"
                    },
                    "wind_gust_spd": 10.316,
                    "timestamp_local": "2020-05-11T14:00:00",
                    "snow_depth": 0,
                    "clouds": 17,
                    "ts": 1589169600,
                    "wind_spd": 5.3845,
                    "pop": 0,
                    "wind_cdir_full": "northwest",
                    "slp": 993.765,
                    "dni": 915.61,
                    "dewpt": 3.2,
                    "snow": 0,
                    "uv": 7.72598,
                    "wind_dir": 305,
                    "clouds_hi": 2,
                    "precip": 0,
                    "vis": 24.1351,
                    "dhi": 120.88,
                    "app_temp": 17.4,
                    "datetime": "2020-05-11:04",
                    "temp": 17.4,
                    "ghi": 925.7,
                    "clouds_mid": 8,
                    "clouds_low": 12
                },
                {
                    "wind_cdir": "NW",
                    "rh": 37,
                    "pod": "d",
                    "timestamp_utc": "2020-05-11T05:00:00",
                    "pres": 987.846,
                    "solar_rad": 848.463,
                    "ozone": 394.201,
                    "weather": {
                        "icon": "c02d",
                        "code": 801,
                        "description": "Few clouds"
                    },
                    "wind_gust_spd": 9.10489,
                    "timestamp_local": "2020-05-11T15:00:00",
                    "snow_depth": 0,
                    "clouds": 15,
                    "ts": 1589173200,
                    "wind_spd": 4.40938,
                    "pop": 0,
                    "wind_cdir_full": "northwest",
                    "slp": 994.018,
                    "dni": 897.25,
                    "dewpt": 2.9,
                    "snow": 0,
                    "uv": 6.72374,
                    "wind_dir": 306,
                    "clouds_hi": 2,
                    "precip": 0,
                    "vis": 24.1351,
                    "dhi": 116.92,
                    "app_temp": 17.9,
                    "datetime": "2020-05-11:05",
                    "temp": 17.9,
                    "ghi": 849.47,
                    "clouds_mid": 6,
                    "clouds_low": 10
                },
                {
                    "wind_cdir": "WNW",
                    "rh": 39,
                    "pod": "d",
                    "timestamp_utc": "2020-05-11T06:00:00",
                    "pres": 987.896,
                    "solar_rad": 723.668,
                    "ozone": 392.331,
                    "weather": {
                        "icon": "c02d",
                        "code": 801,
                        "description": "Few clouds"
                    },
                    "wind_gust_spd": 7.90788,
                    "timestamp_local": "2020-05-11T16:00:00",
                    "snow_depth": 0,
                    "clouds": 12,
                    "ts": 1589176800,
                    "wind_spd": 4.15918,
                    "pop": 0,
                    "wind_cdir_full": "west-northwest",
                    "slp": 994.122,
                    "dni": 862.56,
                    "dewpt": 3.8,
                    "snow": 0,
                    "uv": 5.27869,
                    "wind_dir": 292,
                    "clouds_hi": 2,
                    "precip": 0,
                    "vis": 24.135,
                    "dhi": 109.81,
                    "app_temp": 18.3,
                    "datetime": "2020-05-11:06",
                    "temp": 18.3,
                    "ghi": 724.07,
                    "clouds_mid": 5,
                    "clouds_low": 9
                },
                {
                    "wind_cdir": "WNW",
                    "rh": 40,
                    "pod": "d",
                    "timestamp_utc": "2020-05-11T07:00:00",
                    "pres": 988.09,
                    "solar_rad": 387.739,
                    "ozone": 392.384,
                    "weather": {
                        "icon": "c04d",
                        "code": 804,
                        "description": "Overcast clouds"
                    },
                    "wind_gust_spd": 7.53032,
                    "timestamp_local": "2020-05-11T17:00:00",
                    "snow_depth": 0,
                    "clouds": 77,
                    "ts": 1589180400,
                    "wind_spd": 3.66553,
                    "pop": 0,
                    "wind_cdir_full": "west-northwest",
                    "slp": 994.302,
                    "dni": 805.71,
                    "dewpt": 4.1,
                    "snow": 0,
                    "uv": 1.89369,
                    "wind_dir": 283,
                    "clouds_hi": 0,
                    "precip": 0,
                    "vis": 24.1351,
                    "dhi": 99.12,
                    "app_temp": 18.1,
                    "datetime": "2020-05-11:07",
                    "temp": 18.1,
                    "ghi": 560.65,
                    "clouds_mid": 0,
                    "clouds_low": 77
                },
                {
                    "wind_cdir": "SW",
                    "rh": 46,
                    "pod": "d",
                    "timestamp_utc": "2020-05-11T08:00:00",
                    "pres": 988.54,
                    "solar_rad": 316.212,
                    "ozone": 393.084,
                    "weather": {
                        "icon": "c03d",
                        "code": 803,
                        "description": "Broken clouds"
                    },
                    "wind_gust_spd": 5.8286,
                    "timestamp_local": "2020-05-11T18:00:00",
                    "snow_depth": 0,
                    "clouds": 63,
                    "ts": 1589184000,
                    "wind_spd": 3.325,
                    "pop": 0,
                    "wind_cdir_full": "southwest",
                    "slp": 994.775,
                    "dni": 713.89,
                    "dewpt": 5.7,
                    "snow": 0,
                    "uv": 1.56982,
                    "wind_dir": 235,
                    "clouds_hi": 0,
                    "precip": 0,
                    "vis": 24.1348,
                    "dhi": 83.94,
                    "app_temp": 17.4,
                    "datetime": "2020-05-11:08",
                    "temp": 17.4,
                    "ghi": 374.61,
                    "clouds_mid": 0,
                    "clouds_low": 63
                },
                {
                    "wind_cdir": "SSW",
                    "rh": 53,
                    "pod": "d",
                    "timestamp_utc": "2020-05-11T09:00:00",
                    "pres": 988.899,
                    "solar_rad": 142.601,
                    "ozone": 393.038,
                    "weather": {
                        "icon": "c04d",
                        "code": 804,
                        "description": "Overcast clouds"
                    },
                    "wind_gust_spd": 7.00602,
                    "timestamp_local": "2020-05-11T19:00:00",
                    "snow_depth": 0,
                    "clouds": 71,
                    "ts": 1589187600,
                    "wind_spd": 3.87561,
                    "pop": 0,
                    "wind_cdir_full": "south-southwest",
                    "slp": 994.982,
                    "dni": 554,
                    "dewpt": 6.1,
                    "snow": 0,
                    "uv": 1.08848,
                    "wind_dir": 211,
                    "clouds_hi": 0,
                    "precip": 0,
                    "vis": 24.1349,
                    "dhi": 62.1,
                    "app_temp": 15.7,
                    "datetime": "2020-05-11:09",
                    "temp": 15.7,
                    "ghi": 186.18,
                    "clouds_mid": 0,
                    "clouds_low": 71
                },
                {
                    "wind_cdir": "SSW",
                    "rh": 64,
                    "pod": "d",
                    "timestamp_utc": "2020-05-11T10:00:00",
                    "pres": 989.284,
                    "solar_rad": 25.0137,
                    "ozone": 395.985,
                    "weather": {
                        "icon": "c03d",
                        "code": 803,
                        "description": "Broken clouds"
                    },
                    "wind_gust_spd": 6.50292,
                    "timestamp_local": "2020-05-11T20:00:00",
                    "snow_depth": 0,
                    "clouds": 58,
                    "ts": 1589191200,
                    "wind_spd": 4.28491,
                    "pop": 0,
                    "wind_cdir_full": "south-southwest",
                    "slp": 995.27,
                    "dni": 200.21,
                    "dewpt": 5.8,
                    "snow": 0,
                    "uv": 1.182,
                    "wind_dir": 199,
                    "clouds_hi": 0,
                    "precip": 0,
                    "vis": 24.135,
                    "dhi": 25.9,
                    "app_temp": 12.6,
                    "datetime": "2020-05-11:10",
                    "temp": 12.6,
                    "ghi": 28.35,
                    "clouds_mid": 0,
                    "clouds_low": 58
                },
                {
                    "wind_cdir": "SW",
                    "rh": 62,
                    "pod": "n",
                    "timestamp_utc": "2020-05-11T11:00:00",
                    "pres": 990.074,
                    "solar_rad": 0,
                    "ozone": 397.929,
                    "weather": {
                        "icon": "c03n",
                        "code": 803,
                        "description": "Broken clouds"
                    },
                    "wind_gust_spd": 4.01597,
                    "timestamp_local": "2020-05-11T21:00:00",
                    "snow_depth": 0,
                    "clouds": 46,
                    "ts": 1589194800,
                    "wind_spd": 3.19686,
                    "pop": 0,
                    "wind_cdir_full": "southwest",
                    "slp": 996.15,
                    "dni": 0,
                    "dewpt": 5.1,
                    "snow": 0,
                    "uv": 0,
                    "wind_dir": 216,
                    "clouds_hi": 0,
                    "precip": 0,
                    "vis": 24.1348,
                    "dhi": 0,
                    "app_temp": 12.2,
                    "datetime": "2020-05-11:11",
                    "temp": 12.2,
                    "ghi": 0,
                    "clouds_mid": 0,
                    "clouds_low": 46
                },
                {
                    "wind_cdir": "SSW",
                    "rh": 63,
                    "pod": "n",
                    "timestamp_utc": "2020-05-11T12:00:00",
                    "pres": 990.487,
                    "solar_rad": 0,
                    "ozone": 396.632,
                    "weather": {
                        "icon": "c02n",
                        "code": 802,
                        "description": "Scattered clouds"
                    },
                    "wind_gust_spd": 3.50217,
                    "timestamp_local": "2020-05-11T22:00:00",
                    "snow_depth": 0,
                    "clouds": 38,
                    "ts": 1589198400,
                    "wind_spd": 2.77351,
                    "pop": 0,
                    "wind_cdir_full": "south-southwest",
                    "slp": 996.411,
                    "dni": 0,
                    "dewpt": 4.5,
                    "snow": 0,
                    "uv": 0,
                    "wind_dir": 209,
                    "clouds_hi": 0,
                    "precip": 0,
                    "vis": 24.1351,
                    "dhi": 0,
                    "app_temp": 11.3,
                    "datetime": "2020-05-11:12",
                    "temp": 11.3,
                    "ghi": 0,
                    "clouds_mid": 0,
                    "clouds_low": 38
                },
                {
                    "wind_cdir": "SSW",
                    "rh": 65,
                    "pod": "n",
                    "timestamp_utc": "2020-05-11T13:00:00",
                    "pres": 990.165,
                    "solar_rad": 0,
                    "ozone": 393.546,
                    "weather": {
                        "icon": "c01n",
                        "code": 800,
                        "description": "Clear Sky"
                    },
                    "wind_gust_spd": 2.9,
                    "timestamp_local": "2020-05-11T23:00:00",
                    "snow_depth": 0,
                    "clouds": 0,
                    "ts": 1589202000,
                    "wind_spd": 2.22532,
                    "pop": 0,
                    "wind_cdir_full": "south-southwest",
                    "slp": 996.113,
                    "dni": 0,
                    "dewpt": 4.2,
                    "snow": 0,
                    "uv": 0,
                    "wind_dir": 202,
                    "clouds_hi": 0,
                    "precip": 0,
                    "vis": 24.1352,
                    "dhi": 0,
                    "app_temp": 10.4,
                    "datetime": "2020-05-11:13",
                    "temp": 10.4,
                    "ghi": 0,
                    "clouds_mid": 0,
                    "clouds_low": 0
                },
                {
                    "wind_cdir": "S",
                    "rh": 67,
                    "pod": "n",
                    "timestamp_utc": "2020-05-11T14:00:00",
                    "pres": 990.278,
                    "solar_rad": 0,
                    "ozone": 391.726,
                    "weather": {
                        "icon": "c01n",
                        "code": 800,
                        "description": "Clear Sky"
                    },
                    "wind_gust_spd": 2.82457,
                    "timestamp_local": "2020-05-12T00:00:00",
                    "snow_depth": 0,
                    "clouds": 0,
                    "ts": 1589205600,
                    "wind_spd": 2.21022,
                    "pop": 0,
                    "wind_cdir_full": "south",
                    "slp": 996.048,
                    "dni": 0,
                    "dewpt": 3.9,
                    "snow": 0,
                    "uv": 0,
                    "wind_dir": 178,
                    "clouds_hi": 0,
                    "precip": 0,
                    "vis": 24.1349,
                    "dhi": 0,
                    "app_temp": 9.8,
                    "datetime": "2020-05-11:14",
                    "temp": 9.8,
                    "ghi": 0,
                    "clouds_mid": 0,
                    "clouds_low": 0
                },
                {
                    "wind_cdir": "SE",
                    "rh": 70,
                    "pod": "n",
                    "timestamp_utc": "2020-05-11T15:00:00",
                    "pres": 990.158,
                    "solar_rad": 0,
                    "ozone": 391.626,
                    "weather": {
                        "icon": "c01n",
                        "code": 800,
                        "description": "Clear Sky"
                    },
                    "wind_gust_spd": 3.03971,
                    "timestamp_local": "2020-05-12T01:00:00",
                    "snow_depth": 0,
                    "clouds": 0,
                    "ts": 1589209200,
                    "wind_spd": 2.55706,
                    "pop": 0,
                    "wind_cdir_full": "southeast",
                    "slp": 995.854,
                    "dni": 0,
                    "dewpt": 4,
                    "snow": 0,
                    "uv": 0,
                    "wind_dir": 139,
                    "clouds_hi": 0,
                    "precip": 0,
                    "vis": 24.1351,
                    "dhi": 0,
                    "app_temp": 9.1,
                    "datetime": "2020-05-11:15",
                    "temp": 9.1,
                    "ghi": 0,
                    "clouds_mid": 0,
                    "clouds_low": 0
                },
                {
                    "wind_cdir": "SE",
                    "rh": 74,
                    "pod": "n",
                    "timestamp_utc": "2020-05-11T16:00:00",
                    "pres": 989.917,
                    "solar_rad": 0,
                    "ozone": 395.615,
                    "weather": {
                        "icon": "c01n",
                        "code": 800,
                        "description": "Clear Sky"
                    },
                    "wind_gust_spd": 3.74176,
                    "timestamp_local": "2020-05-12T02:00:00",
                    "snow_depth": 0,
                    "clouds": 1,
                    "ts": 1589212800,
                    "wind_spd": 3.06412,
                    "pop": 0,
                    "wind_cdir_full": "southeast",
                    "slp": 995.298,
                    "dni": 0,
                    "dewpt": 4.1,
                    "snow": 0,
                    "uv": 0,
                    "wind_dir": 144,
                    "clouds_hi": 1,
                    "precip": 0,
                    "vis": 24.135,
                    "dhi": 0,
                    "app_temp": 8.4,
                    "datetime": "2020-05-11:16",
                    "temp": 8.4,
                    "ghi": 0,
                    "clouds_mid": 0,
                    "clouds_low": 0
                },
                {
                    "wind_cdir": "SE",
                    "rh": 77,
                    "pod": "n",
                    "timestamp_utc": "2020-05-11T17:00:00",
                    "pres": 988.908,
                    "solar_rad": 0,
                    "ozone": 396.984,
                    "weather": {
                        "icon": "c02n",
                        "code": 802,
                        "description": "Scattered clouds"
                    },
                    "wind_gust_spd": 3.04269,
                    "timestamp_local": "2020-05-12T03:00:00",
                    "snow_depth": 0,
                    "clouds": 21,
                    "ts": 1589216400,
                    "wind_spd": 2.51454,
                    "pop": 0,
                    "wind_cdir_full": "southeast",
                    "slp": 994.615,
                    "dni": 0,
                    "dewpt": 4.1,
                    "snow": 0,
                    "uv": 0,
                    "wind_dir": 144,
                    "clouds_hi": 21,
                    "precip": 0,
                    "vis": 24.1349,
                    "dhi": 0,
                    "app_temp": 8,
                    "datetime": "2020-05-11:17",
                    "temp": 8,
                    "ghi": 0,
                    "clouds_mid": 0,
                    "clouds_low": 0
                },
                {
                    "wind_cdir": "SSE",
                    "rh": 78,
                    "pod": "n",
                    "timestamp_utc": "2020-05-11T18:00:00",
                    "pres": 988.562,
                    "solar_rad": 0,
                    "ozone": 397.6,
                    "weather": {
                        "icon": "c02n",
                        "code": 802,
                        "description": "Scattered clouds"
                    },
                    "wind_gust_spd": 2.45102,
                    "timestamp_local": "2020-05-12T04:00:00",
                    "snow_depth": 0,
                    "clouds": 34,
                    "ts": 1589220000,
                    "wind_spd": 1.93924,
                    "pop": 0,
                    "wind_cdir_full": "south-southeast",
                    "slp": 994.049,
                    "dni": 0,
                    "dewpt": 4.2,
                    "snow": 0,
                    "uv": 0,
                    "wind_dir": 164,
                    "clouds_hi": 34,
                    "precip": 0,
                    "vis": 24.1351,
                    "dhi": 0,
                    "app_temp": 7.8,
                    "datetime": "2020-05-11:18",
                    "temp": 7.8,
                    "ghi": 0,
                    "clouds_mid": 0,
                    "clouds_low": 0
                },
                {
                    "wind_cdir": "SSW",
                    "rh": 80,
                    "pod": "n",
                    "timestamp_utc": "2020-05-11T19:00:00",
                    "pres": 988.041,
                    "solar_rad": 0,
                    "ozone": 396.222,
                    "weather": {
                        "icon": "c04n",
                        "code": 804,
                        "description": "Overcast clouds"
                    },
                    "wind_gust_spd": 2.32902,
                    "timestamp_local": "2020-05-12T05:00:00",
                    "snow_depth": 0,
                    "clouds": 100,
                    "ts": 1589223600,
                    "wind_spd": 1.78002,
                    "pop": 0,
                    "wind_cdir_full": "south-southwest",
                    "slp": 993.574,
                    "dni": 0,
                    "dewpt": 4.1,
                    "snow": 0,
                    "uv": 0,
                    "wind_dir": 202,
                    "clouds_hi": 100,
                    "precip": 0,
                    "vis": 24.1347,
                    "dhi": 0,
                    "app_temp": 7.5,
                    "datetime": "2020-05-11:19",
                    "temp": 7.5,
                    "ghi": 0,
                    "clouds_mid": 0,
                    "clouds_low": 0
                },
                {
                    "wind_cdir": "SW",
                    "rh": 81,
                    "pod": "d",
                    "timestamp_utc": "2020-05-11T20:00:00",
                    "pres": 987.59,
                    "solar_rad": 0.551,
                    "ozone": 399.961,
                    "weather": {
                        "icon": "c04d",
                        "code": 804,
                        "description": "Overcast clouds"
                    },
                    "wind_gust_spd": 2.73905,
                    "timestamp_local": "2020-05-12T06:00:00",
                    "snow_depth": 0,
                    "clouds": 100,
                    "ts": 1589227200,
                    "wind_spd": 1.95442,
                    "pop": 0,
                    "wind_cdir_full": "southwest",
                    "slp": 993.146,
                    "dni": 26.42,
                    "dewpt": 4.2,
                    "snow": 0,
                    "uv": 0.608395,
                    "wind_dir": 221,
                    "clouds_hi": 100,
                    "precip": 0,
                    "vis": 24.1353,
                    "dhi": 8.46,
                    "app_temp": 7.3,
                    "datetime": "2020-05-11:20",
                    "temp": 7.3,
                    "ghi": 2.9,
                    "clouds_mid": 0,
                    "clouds_low": 0
                }
            ],
            "city_name": "Vladivostok",
            "lon": "131.87353",
            "timezone": "Asia/Vladivostok",
            "lat": "43.10562",
            "country_code": "RU",
            "state_code": "59"
        }
    """.trimIndent()

    private val jsonDaily = """
        {
            "data": [
                {
                    "moonrise_ts": 1589204406,
                    "wind_cdir": "ЗЮЗ",
                    "rh": 69,
                    "pres": 988.314,
                    "high_temp": 18.3,
                    "sunset_ts": 1589192470,
                    "ozone": 393.532,
                    "moon_phase": 0.752008,
                    "wind_gust_spd": 12.801,
                    "snow_depth": 0,
                    "clouds": 38,
                    "ts": 1589119260,
                    "sunrise_ts": 1589140335,
                    "app_min_temp": 8.2,
                    "wind_spd": 3.64441,
                    "pop": 85,
                    "wind_cdir_full": "Западный-Юго-Западный",
                    "slp": 994.399,
                    "moon_phase_lunation": 0.61,
                    "valid_date": "2020-05-11",
                    "app_max_temp": 18.3,
                    "vis": 22.5166,
                    "dewpt": 6.3,
                    "snow": 0,
                    "uv": 7.91822,
                    "weather": {
                        "icon": "r01d",
                        "code": 500,
                        "description": "Небольшой дождь"
                    },
                    "wind_dir": 243,
                    "max_dhi": null,
                    "clouds_hi": 13,
                    "precip": 6.375,
                    "low_temp": 7.3,
                    "max_temp": 18.4,
                    "moonset_ts": 1589154483,
                    "datetime": "2020-05-11",
                    "temp": 12.7,
                    "min_temp": 7.9,
                    "clouds_mid": 20,
                    "clouds_low": 23
                },
                {
                    "moonrise_ts": 1589207936,
                    "wind_cdir": "ЮЮЗ",
                    "rh": 74,
                    "pres": 988.065,
                    "high_temp": 13.8,
                    "sunset_ts": 1589278934,
                    "ozone": 408.77,
                    "moon_phase": 0.653078,
                    "wind_gust_spd": 9.61083,
                    "snow_depth": 0,
                    "clouds": 66,
                    "ts": 1589205660,
                    "sunrise_ts": 1589226668,
                    "app_min_temp": 3.7,
                    "wind_spd": 3.05347,
                    "pop": 75,
                    "wind_cdir_full": "Юго-Юго-Западный",
                    "slp": 993.896,
                    "moon_phase_lunation": 0.64,
                    "valid_date": "2020-05-12",
                    "app_max_temp": 13.8,
                    "vis": 22.198,
                    "dewpt": 5.5,
                    "snow": 0,
                    "uv": 5.0971,
                    "weather": {
                        "icon": "c03d",
                        "code": 803,
                        "description": "Облачно с прояснениями"
                    },
                    "wind_dir": 210,
                    "max_dhi": null,
                    "clouds_hi": 50,
                    "precip": 2.8125,
                    "low_temp": 4.9,
                    "max_temp": 14.8,
                    "moonset_ts": 1589244603,
                    "datetime": "2020-05-12",
                    "temp": 10.1,
                    "min_temp": 6.4,
                    "clouds_mid": 28,
                    "clouds_low": 26
                },
                {
                    "moonrise_ts": 1589297279,
                    "wind_cdir": "ЗЮЗ",
                    "rh": 63,
                    "pres": 996.123,
                    "high_temp": 15.7,
                    "sunset_ts": 1589365398,
                    "ozone": 409.767,
                    "moon_phase": 0.550535,
                    "wind_gust_spd": 6.13436,
                    "snow_depth": 0,
                    "clouds": 62,
                    "ts": 1589292060,
                    "sunrise_ts": 1589313003,
                    "app_min_temp": 1.2,
                    "wind_spd": 1.77692,
                    "pop": 20,
                    "wind_cdir_full": "Западный-Юго-Западный",
                    "slp": 1002.25,
                    "moon_phase_lunation": 0.67,
                    "valid_date": "2020-05-13",
                    "app_max_temp": 15.7,
                    "vis": 24.017,
                    "dewpt": 3,
                    "snow": 0,
                    "uv": 3.65581,
                    "weather": {
                        "icon": "c03d",
                        "code": 803,
                        "description": "Облачно с прояснениями"
                    },
                    "wind_dir": 240,
                    "max_dhi": null,
                    "clouds_hi": 0,
                    "precip": 0.0625,
                    "low_temp": 5.8,
                    "max_temp": 16.2,
                    "moonset_ts": 1589334793,
                    "datetime": "2020-05-13",
                    "temp": 10.4,
                    "min_temp": 4.9,
                    "clouds_mid": 37,
                    "clouds_low": 46
                },
                {
                    "moonrise_ts": 1589386093,
                    "wind_cdir": "Ю",
                    "rh": 71,
                    "pres": 1003.01,
                    "high_temp": 14.9,
                    "sunset_ts": 1589451861,
                    "ozone": 375.651,
                    "moon_phase": 0.448697,
                    "wind_gust_spd": 7.10122,
                    "snow_depth": 0,
                    "clouds": 24,
                    "ts": 1589378460,
                    "sunrise_ts": 1589399339,
                    "app_min_temp": 3.3,
                    "wind_spd": 2.31049,
                    "pop": 60,
                    "wind_cdir_full": "Южный",
                    "slp": 1008.42,
                    "moon_phase_lunation": 0.71,
                    "valid_date": "2020-05-14",
                    "app_max_temp": 14.9,
                    "vis": 23.7784,
                    "dewpt": 5.4,
                    "snow": 0,
                    "uv": 9.26803,
                    "weather": {
                        "icon": "c02d",
                        "code": 802,
                        "description": "Местами облачно"
                    },
                    "wind_dir": 171,
                    "max_dhi": null,
                    "clouds_hi": 13,
                    "precip": 1.5,
                    "low_temp": 7.8,
                    "max_temp": 15.3,
                    "moonset_ts": 1589424950,
                    "datetime": "2020-05-14",
                    "temp": 10.8,
                    "min_temp": 6.5,
                    "clouds_mid": 1,
                    "clouds_low": 10
                },
                {
                    "moonrise_ts": 1589474486,
                    "wind_cdir": "ЮЮЗ",
                    "rh": 86,
                    "pres": 1005.55,
                    "high_temp": 14.5,
                    "sunset_ts": 1589538323,
                    "ozone": 367.191,
                    "moon_phase": 0.448697,
                    "wind_gust_spd": 13.0199,
                    "snow_depth": 0,
                    "clouds": 86,
                    "ts": 1589464860,
                    "sunrise_ts": 1589485677,
                    "app_min_temp": 8.4,
                    "wind_spd": 3.67039,
                    "pop": 75,
                    "wind_cdir_full": "Юго-Юго-Западный",
                    "slp": 1010.34,
                    "moon_phase_lunation": 0.74,
                    "valid_date": "2020-05-15",
                    "app_max_temp": 14.5,
                    "vis": 21.9736,
                    "dewpt": 8.2,
                    "snow": 0,
                    "uv": 4.95349,
                    "weather": {
                        "icon": "r04d",
                        "code": 520,
                        "description": "Местами небольшой дождь"
                    },
                    "wind_dir": 202,
                    "max_dhi": null,
                    "clouds_hi": 82,
                    "precip": 3.125,
                    "low_temp": 7.6,
                    "max_temp": 14.7,
                    "moonset_ts": 1589511350,
                    "datetime": "2020-05-15",
                    "temp": 10.5,
                    "min_temp": 8,
                    "clouds_mid": 46,
                    "clouds_low": 7
                },
                {
                    "moonrise_ts": 1589562575,
                    "wind_cdir": "ЮЮЗ",
                    "rh": 87,
                    "pres": 1002.46,
                    "high_temp": 9.2,
                    "sunset_ts": 1589624785,
                    "ozone": 369.127,
                    "moon_phase": 0.350948,
                    "wind_gust_spd": 16.3082,
                    "snow_depth": 0,
                    "clouds": 97,
                    "ts": 1589551260,
                    "sunrise_ts": 1589572017,
                    "app_min_temp": 7.4,
                    "wind_spd": 6.31042,
                    "pop": 60,
                    "wind_cdir_full": "Юго-Юго-Западный",
                    "slp": 1008,
                    "moon_phase_lunation": 0.78,
                    "valid_date": "2020-05-16",
                    "app_max_temp": 9.5,
                    "vis": 22.3084,
                    "dewpt": 6.1,
                    "snow": 0,
                    "uv": 3.60598,
                    "weather": {
                        "icon": "c04d",
                        "code": 804,
                        "description": "Облачно"
                    },
                    "wind_dir": 198,
                    "max_dhi": null,
                    "clouds_hi": 13,
                    "precip": 1.5,
                    "low_temp": 7.4,
                    "max_temp": 9.5,
                    "moonset_ts": 1589601427,
                    "datetime": "2020-05-16",
                    "temp": 8.2,
                    "min_temp": 7.2,
                    "clouds_mid": 22,
                    "clouds_low": 94
                },
                {
                    "moonrise_ts": 1589650462,
                    "wind_cdir": "З",
                    "rh": 97,
                    "pres": 994.709,
                    "high_temp": 14.3,
                    "sunset_ts": 1589711247,
                    "ozone": 374.856,
                    "moon_phase": 0.260117,
                    "wind_gust_spd": 11.8211,
                    "snow_depth": 0,
                    "clouds": 100,
                    "ts": 1589637660,
                    "sunrise_ts": 1589658358,
                    "app_min_temp": 7.6,
                    "wind_spd": 3.96604,
                    "pop": 100,
                    "wind_cdir_full": "Западный",
                    "slp": 1000.52,
                    "moon_phase_lunation": 0.81,
                    "valid_date": "2020-05-17",
                    "app_max_temp": 10.2,
                    "vis": 8.72338,
                    "dewpt": 8.1,
                    "snow": 0,
                    "uv": 2.89962,
                    "weather": {
                        "icon": "r03d",
                        "code": 502,
                        "description": "Ливень"
                    },
                    "wind_dir": 267,
                    "max_dhi": null,
                    "clouds_hi": 100,
                    "precip": 51.25,
                    "low_temp": 9.3,
                    "max_temp": 10.3,
                    "moonset_ts": 1589691430,
                    "datetime": "2020-05-17",
                    "temp": 8.6,
                    "min_temp": 7.2,
                    "clouds_mid": 98,
                    "clouds_low": 100
                },
                {
                    "moonrise_ts": 1589738229,
                    "wind_cdir": "Ю",
                    "rh": 81,
                    "pres": 1003,
                    "high_temp": 7.8,
                    "sunset_ts": 1589797708,
                    "ozone": 361.257,
                    "moon_phase": 0.17883,
                    "wind_gust_spd": 13.635,
                    "snow_depth": 0,
                    "clouds": 99,
                    "ts": 1589724060,
                    "sunrise_ts": 1589744701,
                    "app_min_temp": 7.8,
                    "wind_spd": 5.67578,
                    "pop": 0,
                    "wind_cdir_full": "Южный",
                    "slp": 1008.93,
                    "moon_phase_lunation": 0.84,
                    "valid_date": "2020-05-18",
                    "app_max_temp": 14.3,
                    "vis": 24.135,
                    "dewpt": 7.4,
                    "snow": 0,
                    "uv": 2.9851,
                    "weather": {
                        "icon": "c04d",
                        "code": 804,
                        "description": "Облачно"
                    },
                    "wind_dir": 172,
                    "max_dhi": null,
                    "clouds_hi": 94,
                    "precip": 0,
                    "low_temp": 6.7,
                    "max_temp": 15.9,
                    "moonset_ts": 1589781388,
                    "datetime": "2020-05-18",
                    "temp": 10.6,
                    "min_temp": 7.5,
                    "clouds_mid": 17,
                    "clouds_low": 77
                },
                {
                    "moonrise_ts": 1589825950,
                    "wind_cdir": "ЮЮЗ",
                    "rh": 91,
                    "pres": 1009.36,
                    "high_temp": 8.3,
                    "sunset_ts": 1589884168,
                    "ozone": 362.214,
                    "moon_phase": 0.109728,
                    "wind_gust_spd": 9.70042,
                    "snow_depth": 0,
                    "clouds": 100,
                    "ts": 1589810460,
                    "sunrise_ts": 1589831046,
                    "app_min_temp": 3.1,
                    "wind_spd": 4.10867,
                    "pop": 75,
                    "wind_cdir_full": "Юго-Юго-Западный",
                    "slp": 1014.92,
                    "moon_phase_lunation": 0.88,
                    "valid_date": "2020-05-19",
                    "app_max_temp": 7.8,
                    "vis": 22.6807,
                    "dewpt": 5.8,
                    "snow": 0,
                    "uv": 2.92631,
                    "weather": {
                        "icon": "c04d",
                        "code": 804,
                        "description": "Облачно"
                    },
                    "wind_dir": 203,
                    "max_dhi": null,
                    "clouds_hi": 99,
                    "precip": 2.9375,
                    "low_temp": 6.3,
                    "max_temp": 8,
                    "moonset_ts": 1589871345,
                    "datetime": "2020-05-19",
                    "temp": 7.1,
                    "min_temp": 6.3,
                    "clouds_mid": 76,
                    "clouds_low": 97
                },
                {
                    "moonrise_ts": 1589913688,
                    "wind_cdir": "Ю",
                    "rh": 95,
                    "pres": 1008.45,
                    "high_temp": 15.8,
                    "sunset_ts": 1589970627,
                    "ozone": 364.688,
                    "moon_phase": 0.0554831,
                    "wind_gust_spd": 9.83311,
                    "snow_depth": 0,
                    "clouds": 100,
                    "ts": 1589896860,
                    "sunrise_ts": 1589917393,
                    "app_min_temp": 3,
                    "wind_spd": 4.0243,
                    "pop": 80,
                    "wind_cdir_full": "Южный",
                    "slp": 1013.77,
                    "moon_phase_lunation": 0.91,
                    "valid_date": "2020-05-20",
                    "app_max_temp": 8.3,
                    "vis": 19.1145,
                    "dewpt": 6.5,
                    "snow": 0,
                    "uv": 2.93695,
                    "weather": {
                        "icon": "r04d",
                        "code": 520,
                        "description": "Местами небольшой дождь"
                    },
                    "wind_dir": 185,
                    "max_dhi": null,
                    "clouds_hi": 40,
                    "precip": 4.375,
                    "low_temp": 7.2,
                    "max_temp": 8.8,
                    "moonset_ts": 1589961345,
                    "datetime": "2020-05-20",
                    "temp": 7.3,
                    "min_temp": 6.3,
                    "clouds_mid": 63,
                    "clouds_low": 100
                },
                {
                    "moonrise_ts": 1590001511,
                    "wind_cdir": "Ю",
                    "rh": 92,
                    "pres": 1008.64,
                    "high_temp": 16.4,
                    "sunset_ts": 1590057086,
                    "ozone": 379.588,
                    "moon_phase": 0.0186642,
                    "wind_gust_spd": 8.50436,
                    "snow_depth": 0,
                    "clouds": 92,
                    "ts": 1589983260,
                    "sunrise_ts": 1590003742,
                    "app_min_temp": 8.3,
                    "wind_spd": 3.94312,
                    "pop": 0,
                    "wind_cdir_full": "Южный",
                    "slp": 1013.76,
                    "moon_phase_lunation": 0.94,
                    "valid_date": "2020-05-21",
                    "app_max_temp": 8.7,
                    "vis": 24.1349,
                    "dewpt": 7.3,
                    "snow": 0,
                    "uv": 1.85507,
                    "weather": {
                        "icon": "c04d",
                        "code": 804,
                        "description": "Облачно"
                    },
                    "wind_dir": 182,
                    "max_dhi": null,
                    "clouds_hi": 43,
                    "precip": 0,
                    "low_temp": 12.1,
                    "max_temp": 10.6,
                    "moonset_ts": 1590051417,
                    "datetime": "2020-05-21",
                    "temp": 8.5,
                    "min_temp": 8.1,
                    "clouds_mid": 12,
                    "clouds_low": 88
                },
                {
                    "moonrise_ts": 1590089492,
                    "wind_cdir": "Ю",
                    "rh": 91,
                    "pres": 1008.37,
                    "high_temp": 11.3,
                    "sunset_ts": 1590143543,
                    "ozone": 379.42,
                    "moon_phase": 0.00150681,
                    "wind_gust_spd": 6.51752,
                    "snow_depth": 0,
                    "clouds": 100,
                    "ts": 1590069660,
                    "sunrise_ts": 1590090092,
                    "app_min_temp": 9.8,
                    "wind_spd": 3.51324,
                    "pop": 20,
                    "wind_cdir_full": "Южный",
                    "slp": 1013.44,
                    "moon_phase_lunation": 0.98,
                    "valid_date": "2020-05-22",
                    "app_max_temp": 10.8,
                    "vis": 23.2856,
                    "dewpt": 8.9,
                    "snow": 0,
                    "uv": 1.70672,
                    "weather": {
                        "icon": "c04d",
                        "code": 804,
                        "description": "Облачно"
                    },
                    "wind_dir": 170,
                    "max_dhi": null,
                    "clouds_hi": 92,
                    "precip": 0.0625,
                    "low_temp": 11.1,
                    "max_temp": 12.9,
                    "moonset_ts": 1590141567,
                    "datetime": "2020-05-22",
                    "temp": 10.3,
                    "min_temp": 9.8,
                    "clouds_mid": 0,
                    "clouds_low": 94
                },
                {
                    "moonrise_ts": 1590177714,
                    "wind_cdir": "Ю",
                    "rh": 92,
                    "pres": 1003.78,
                    "high_temp": 15.7,
                    "sunset_ts": 1590230000,
                    "ozone": 351.527,
                    "moon_phase": 0.00565028,
                    "wind_gust_spd": 5.90129,
                    "snow_depth": 0,
                    "clouds": 78,
                    "ts": 1590156060,
                    "sunrise_ts": 1590176444,
                    "app_min_temp": 10.6,
                    "wind_spd": 2.81034,
                    "pop": 0,
                    "wind_cdir_full": "Южный",
                    "slp": 1008.7,
                    "moon_phase_lunation": 0.01,
                    "valid_date": "2020-05-23",
                    "app_max_temp": 12,
                    "vis": 24.1349,
                    "dewpt": 10,
                    "snow": 0,
                    "uv": 1.72167,
                    "weather": {
                        "icon": "c04d",
                        "code": 804,
                        "description": "Облачно"
                    },
                    "wind_dir": 184,
                    "max_dhi": null,
                    "clouds_hi": 28,
                    "precip": 0,
                    "low_temp": 9.6,
                    "max_temp": 15.7,
                    "moonset_ts": 1590231756,
                    "datetime": "2020-05-23",
                    "temp": 11.3,
                    "min_temp": 9.6,
                    "clouds_mid": 0,
                    "clouds_low": 54
                },
                {
                    "moonrise_ts": 1590266273,
                    "wind_cdir": "Ю",
                    "rh": 79,
                    "pres": 996.028,
                    "high_temp": 17,
                    "sunset_ts": 1590316456,
                    "ozone": 351.658,
                    "moon_phase": 0.0318897,
                    "wind_gust_spd": 5.80767,
                    "snow_depth": 0,
                    "clouds": 98,
                    "ts": 1590242460,
                    "sunrise_ts": 1590262798,
                    "app_min_temp": 12.1,
                    "wind_spd": 2.27772,
                    "pop": 0,
                    "wind_cdir_full": "Южный",
                    "slp": 1001.87,
                    "moon_phase_lunation": 0.05,
                    "valid_date": "2020-05-24",
                    "app_max_temp": 15.8,
                    "vis": 24.1349,
                    "dewpt": 10.3,
                    "snow": 0,
                    "uv": 1.81319,
                    "weather": {
                        "icon": "c04d",
                        "code": 804,
                        "description": "Облачно"
                    },
                    "wind_dir": 170,
                    "max_dhi": null,
                    "clouds_hi": 98,
                    "precip": 0,
                    "low_temp": 9.2,
                    "max_temp": 17,
                    "moonset_ts": 1590321893,
                    "datetime": "2020-05-24",
                    "temp": 13.9,
                    "min_temp": 9.2,
                    "clouds_mid": 10,
                    "clouds_low": 0
                },
                {
                    "moonrise_ts": 1590355258,
                    "wind_cdir": "ЮЮВ",
                    "rh": 84,
                    "pres": 1000.43,
                    "high_temp": 15.2,
                    "sunset_ts": 1590402911,
                    "ozone": 353.94,
                    "moon_phase": 0.0799868,
                    "wind_gust_spd": 7.80124,
                    "snow_depth": 0,
                    "clouds": 52,
                    "ts": 1590328860,
                    "sunrise_ts": 1590349155,
                    "app_min_temp": 11.3,
                    "wind_spd": 2.84104,
                    "pop": 0,
                    "wind_cdir_full": "Юго-Юго-Восточный",
                    "slp": 1005.81,
                    "moon_phase_lunation": 0.08,
                    "valid_date": "2020-05-25",
                    "app_max_temp": 16.4,
                    "vis": 24.1349,
                    "dewpt": 10.9,
                    "snow": 0,
                    "uv": 5.44869,
                    "weather": {
                        "icon": "c03d",
                        "code": 803,
                        "description": "Облачно с прояснениями"
                    },
                    "wind_dir": 157,
                    "max_dhi": null,
                    "clouds_hi": 52,
                    "precip": 0,
                    "low_temp": 10.6,
                    "max_temp": 16.4,
                    "moonset_ts": 1590411842,
                    "datetime": "2020-05-25",
                    "temp": 13.8,
                    "min_temp": 10.6,
                    "clouds_mid": 3,
                    "clouds_low": 20
                },
                {
                    "moonrise_ts": 1590444731,
                    "wind_cdir": "ЮЮВ",
                    "rh": 99,
                    "pres": 1001.45,
                    "high_temp": 12.6,
                    "sunset_ts": 1590489365,
                    "ozone": 356.758,
                    "moon_phase": 0.148584,
                    "wind_gust_spd": 10.6348,
                    "snow_depth": 0,
                    "clouds": 100,
                    "ts": 1590415260,
                    "sunrise_ts": 1590435513,
                    "app_min_temp": 11.1,
                    "wind_spd": 5.30043,
                    "pop": 70,
                    "wind_cdir_full": "Юго-Юго-Восточный",
                    "slp": 1006.3,
                    "moon_phase_lunation": 0.11,
                    "valid_date": "2020-05-26",
                    "app_max_temp": 11.3,
                    "vis": 0.682899,
                    "dewpt": 11,
                    "snow": 0,
                    "uv": 1.74292,
                    "weather": {
                        "icon": "c04d",
                        "code": 804,
                        "description": "Облачно"
                    },
                    "wind_dir": 165,
                    "max_dhi": null,
                    "clouds_hi": 74,
                    "precip": 2.1875,
                    "low_temp": 11.3,
                    "max_temp": 12.6,
                    "moonset_ts": 1590501471,
                    "datetime": "2020-05-26",
                    "temp": 11.2,
                    "min_temp": 11.1,
                    "clouds_mid": 46,
                    "clouds_low": 99
                }
            ],
            "city_name": "Vladivostok",
            "lon": "131.87353",
            "timezone": "Asia/Vladivostok",
            "lat": "43.10562",
            "country_code": "RU",
            "state_code": "59"
        }
    """.trimIndent()

    private val jsonCurrent = """
      {
          "data": [
              {
                  "rh": 86,
                  "pod": "n",
                  "lon": 131.87353,
                  "pres": 986.849,
                  "timezone": "Asia/Vladivostok",
                  "ob_time": "2020-05-10 20:29",
                  "country_code": "RU",
                  "clouds": 19,
                  "ts": 1589142593,
                  "solar_rad": 133.597,
                  "state_code": "59",
                  "city_name": "Vladivostok",
                  "wind_spd": 3.38787,
                  "last_ob_time": "2020-05-10T20:00:00",
                  "wind_cdir_full": "west-southwest",
                  "wind_cdir": "WSW",
                  "slp": 993.271,
                  "vis": 24.1351,
                  "h_angle": -90,
                  "sunset": "10:25",
                  "dni": 481.44,
                  "dewpt": 6.5,
                  "snow": 0,
                  "uv": 1.76731,
                  "precip": 0,
                  "wind_dir": 255,
                  "sunrise": "20:18",
                  "ghi": 133.98,
                  "dhi": 53.63,
                  "aqi": 78,
                  "lat": 43.10562,
                  "weather": {
                      "icon": "c01n",
                      "code": "800",
                      "description": "Clear sky"
                  },
                  "datetime": "2020-05-10:20",
                  "temp": 8.6,
                  "station": "RKNY",
                  "elev_angle": 0.28,
                  "app_temp": 8.6
              }
          ],
          "count": 1
      }
    """.trimIndent()

}