/*
 * Сreated by Igor Pokrovsky. 2020/4/29
 */

package com.nigtime.weatherapplication.utility.testing

import com.google.gson.Gson
import com.nigtime.weatherapplication.net.json.JsonCurrentForecast
import com.nigtime.weatherapplication.net.json.JsonDailyForecast
import com.nigtime.weatherapplication.net.json.JsonHourlyForecast


object FakeJsonDataProvider {
    private val gson = lazy {
        Gson()
    }

    fun getHourlyForecast(): JsonHourlyForecast =
        gson.value.fromJson<JsonHourlyForecast>(jsonHourly, JsonHourlyForecast::class.java)

    fun getDailyForecast(): JsonDailyForecast =
        gson.value.fromJson<JsonDailyForecast>(jsonDaily, JsonDailyForecast::class.java)

    fun getCurrentForecast(): JsonCurrentForecast =
        gson.value.fromJson<JsonCurrentForecast>(jsonCurrent, JsonCurrentForecast::class.java)


    private val jsonHourly = """
        {
            "data": [
                {
                    "wind_cdir": "Ю",
                    "rh": 81,
                    "pod": "d",
                    "timestamp_utc": "2020-03-03T09:00:00",
                    "pres": 941.061,
                    "solar_rad": 149.194,
                    "ozone": 316.804,
                    "weather": {
                        "icon": "r01d",
                        "code": 500,
                        "description": "Небольшой дождь"
                    },
                    "wind_gust_spd": 13.5185,
                    "timestamp_local": "2020-03-03T10:00:00",
                    "snow_depth": 0,
                    "clouds": 91,
                    "ts": 1583226000,
                    "wind_spd": 1.92655,
                    "pop": 45,
                    "wind_cdir_full": "Южный",
                    "slp": 1010.42,
                    "dni": 729.02,
                    "dewpt": 3.2,
                    "snow": 0,
                    "uv": 1.03687,
                    "wind_dir": 170,
                    "clouds_hi": 44,
                    "precip": 0.8515625,
                    "vis": 11.3548,
                    "dhi": 83.67,
                    "app_temp": 2.4,
                    "datetime": "2020-03-03:09",
                    "temp": 5.8,
                    "ghi": 361.94,
                    "clouds_mid": 86,
                    "clouds_low": 73
                },
                {
                    "wind_cdir": "ССЗ",
                    "rh": 76,
                    "pod": "d",
                    "timestamp_utc": "2020-03-03T10:00:00",
                    "pres": 941.957,
                    "solar_rad": 166.169,
                    "ozone": 314.367,
                    "weather": {
                        "icon": "r01d",
                        "code": 500,
                        "description": "Небольшой дождь"
                    },
                    "wind_gust_spd": 12.9098,
                    "timestamp_local": "2020-03-03T11:00:00",
                    "snow_depth": 0,
                    "clouds": 97,
                    "ts": 1583229600,
                    "wind_spd": 3.04957,
                    "pop": 20,
                    "wind_cdir_full": "Северо-Северо-Западный",
                    "slp": 1010.65,
                    "dni": 811.73,
                    "dewpt": 4,
                    "snow": 0,
                    "uv": 1.21683,
                    "wind_dir": 344,
                    "clouds_hi": 47,
                    "precip": 0.248046875,
                    "vis": 3.87025,
                    "dhi": 96.7,
                    "app_temp": 7.6,
                    "datetime": "2020-03-03:10",
                    "temp": 7.6,
                    "ghi": 513.21,
                    "clouds_mid": 96,
                    "clouds_low": 87
                },
                {
                    "wind_cdir": "ЗСЗ",
                    "rh": 79,
                    "pod": "d",
                    "timestamp_utc": "2020-03-03T11:00:00",
                    "pres": 941.721,
                    "solar_rad": 155.083,
                    "ozone": 314.054,
                    "weather": {
                        "icon": "r01d",
                        "code": 500,
                        "description": "Небольшой дождь"
                    },
                    "wind_gust_spd": 13.3536,
                    "timestamp_local": "2020-03-03T12:00:00",
                    "snow_depth": 0,
                    "clouds": 100,
                    "ts": 1583233200,
                    "wind_spd": 2.49335,
                    "pop": 40,
                    "wind_cdir_full": "Западный-Северо-Западный",
                    "slp": 1010.45,
                    "dni": 855.92,
                    "dewpt": 4.6,
                    "snow": 0,
                    "uv": 1.42443,
                    "wind_dir": 302,
                    "clouds_hi": 100,
                    "precip": 0.73828125,
                    "vis": 4.1352,
                    "dhi": 104.42,
                    "app_temp": 7.5,
                    "datetime": "2020-03-03:11",
                    "temp": 7.5,
                    "ghi": 620.33,
                    "clouds_mid": 77,
                    "clouds_low": 86
                },
                {
                    "wind_cdir": "ССЗ",
                    "rh": 79,
                    "pod": "d",
                    "timestamp_utc": "2020-03-03T12:00:00",
                    "pres": 941.513,
                    "solar_rad": 464.796,
                    "ozone": 311.2,
                    "weather": {
                        "icon": "c02d",
                        "code": 802,
                        "description": "Местами облачно"
                    },
                    "wind_gust_spd": 11.3933,
                    "timestamp_local": "2020-03-03T13:00:00",
                    "snow_depth": 0,
                    "clouds": 77,
                    "ts": 1583236800,
                    "wind_spd": 2.49403,
                    "pop": 0,
                    "wind_cdir_full": "Северо-Северо-Западный",
                    "slp": 1009.91,
                    "dni": 874.36,
                    "dewpt": 6.6,
                    "snow": 0,
                    "uv": 2.4118,
                    "wind_dir": 334,
                    "clouds_hi": 4,
                    "precip": 0,
                    "vis": 24.1349,
                    "dhi": 107.82,
                    "app_temp": 9.5,
                    "datetime": "2020-03-03:12",
                    "temp": 9.5,
                    "ghi": 672.07,
                    "clouds_mid": 56,
                    "clouds_low": 70
                },
                {
                    "wind_cdir": "СЗ",
                    "rh": 73,
                    "pod": "d",
                    "timestamp_utc": "2020-03-03T13:00:00",
                    "pres": 940.514,
                    "solar_rad": 440.102,
                    "ozone": 312.13,
                    "weather": {
                        "icon": "r04d",
                        "code": 520,
                        "description": "Местами небольшой дождь"
                    },
                    "wind_gust_spd": 12.5718,
                    "timestamp_local": "2020-03-03T14:00:00",
                    "snow_depth": 0,
                    "clouds": 79,
                    "ts": 1583240400,
                    "wind_spd": 3.00138,
                    "pop": 20,
                    "wind_cdir_full": "Северо-Западный",
                    "slp": 1008.27,
                    "dni": 871.35,
                    "dewpt": 7.5,
                    "snow": 0,
                    "uv": 2.27788,
                    "wind_dir": 315,
                    "clouds_hi": 20,
                    "precip": 0.2265625,
                    "vis": 24.1347,
                    "dhi": 107.26,
                    "app_temp": 11.2,
                    "datetime": "2020-03-03:13",
                    "temp": 11.2,
                    "ghi": 663.31,
                    "clouds_mid": 65,
                    "clouds_low": 67
                },
                {
                    "wind_cdir": "СЗ",
                    "rh": 55,
                    "pod": "d",
                    "timestamp_utc": "2020-03-03T14:00:00",
                    "pres": 940.156,
                    "solar_rad": 462.225,
                    "ozone": 312.166,
                    "weather": {
                        "icon": "c02d",
                        "code": 802,
                        "description": "Местами облачно"
                    },
                    "wind_gust_spd": 27.0289,
                    "timestamp_local": "2020-03-03T15:00:00",
                    "snow_depth": 0,
                    "clouds": 70,
                    "ts": 1583244000,
                    "wind_spd": 13.4857,
                    "pop": 10,
                    "wind_cdir_full": "Северо-Западный",
                    "slp": 1007.02,
                    "dni": 846.23,
                    "dewpt": 6.4,
                    "snow": 0,
                    "uv": 2.24325,
                    "wind_dir": 314,
                    "clouds_hi": 19,
                    "precip": 0.13671875,
                    "vis": 24.1352,
                    "dhi": 102.68,
                    "app_temp": 15.2,
                    "datetime": "2020-03-03:14",
                    "temp": 15.2,
                    "ghi": 594.92,
                    "clouds_mid": 43,
                    "clouds_low": 50
                },
                {
                    "wind_cdir": "СЗ",
                    "rh": 55,
                    "pod": "d",
                    "timestamp_utc": "2020-03-03T15:00:00",
                    "pres": 941.512,
                    "solar_rad": 471.987,
                    "ozone": 311.179,
                    "weather": {
                        "icon": "r04d",
                        "code": 520,
                        "description": "Местами небольшой дождь"
                    },
                    "wind_gust_spd": 31.8618,
                    "timestamp_local": "2020-03-03T16:00:00",
                    "snow_depth": 0,
                    "clouds": 21,
                    "ts": 1583247600,
                    "wind_spd": 14.762,
                    "pop": 15,
                    "wind_cdir_full": "Северо-Западный",
                    "slp": 1008.39,
                    "dni": 792.91,
                    "dewpt": 6,
                    "snow": 0,
                    "uv": 2.94845,
                    "wind_dir": 319,
                    "clouds_hi": 0,
                    "precip": 0.1484375,
                    "vis": 24.135,
                    "dhi": 93.59,
                    "app_temp": 14.8,
                    "datetime": "2020-03-03:15",
                    "temp": 14.8,
                    "ghi": 473.75,
                    "clouds_mid": 0,
                    "clouds_low": 21
                },
                {
                    "wind_cdir": "СЗ",
                    "rh": 54,
                    "pod": "d",
                    "timestamp_utc": "2020-03-03T16:00:00",
                    "pres": 943.475,
                    "solar_rad": 312.667,
                    "ozone": 310.04,
                    "weather": {
                        "icon": "c01d",
                        "code": 800,
                        "description": "Ясно"
                    },
                    "wind_gust_spd": 31.086,
                    "timestamp_local": "2020-03-03T17:00:00",
                    "snow_depth": 0,
                    "clouds": 14,
                    "ts": 1583251200,
                    "wind_spd": 14.4173,
                    "pop": 0,
                    "wind_cdir_full": "Северо-Западный",
                    "slp": 1010.73,
                    "dni": 694.36,
                    "dewpt": 4,
                    "snow": 0,
                    "uv": 2.36896,
                    "wind_dir": 312,
                    "clouds_hi": 6,
                    "precip": 0,
                    "vis": 24.1353,
                    "dhi": 78.68,
                    "app_temp": 13,
                    "datetime": "2020-03-03:16",
                    "temp": 13,
                    "ghi": 312.96,
                    "clouds_mid": 0,
                    "clouds_low": 9
                },
                {
                    "wind_cdir": "СЗ",
                    "rh": 68,
                    "pod": "d",
                    "timestamp_utc": "2020-03-03T17:00:00",
                    "pres": 945.498,
                    "solar_rad": 124.842,
                    "ozone": 310.311,
                    "weather": {
                        "icon": "c02d",
                        "code": 802,
                        "description": "Местами облачно"
                    },
                    "wind_gust_spd": 29.4945,
                    "timestamp_local": "2020-03-03T18:00:00",
                    "snow_depth": 0,
                    "clouds": 50,
                    "ts": 1583254800,
                    "wind_spd": 11.9228,
                    "pop": 0,
                    "wind_cdir_full": "Северо-Западный",
                    "slp": 1013.38,
                    "dni": 497,
                    "dewpt": 5.8,
                    "snow": 0,
                    "uv": 1.44103,
                    "wind_dir": 319,
                    "clouds_hi": 4,
                    "precip": 0,
                    "vis": 24.1347,
                    "dhi": 54.33,
                    "app_temp": 11.2,
                    "datetime": "2020-03-03:17",
                    "temp": 11.2,
                    "ghi": 134.39,
                    "clouds_mid": 0,
                    "clouds_low": 50
                },
                {
                    "wind_cdir": "СЗ",
                    "rh": 76,
                    "pod": "n",
                    "timestamp_utc": "2020-03-03T18:00:00",
                    "pres": 946.89,
                    "solar_rad": 0,
                    "ozone": 306.547,
                    "weather": {
                        "icon": "c02n",
                        "code": 802,
                        "description": "Местами облачно"
                    },
                    "wind_gust_spd": 23.2042,
                    "timestamp_local": "2020-03-03T19:00:00",
                    "snow_depth": 0,
                    "clouds": 49,
                    "ts": 1583258400,
                    "wind_spd": 8.26987,
                    "pop": 0,
                    "wind_cdir_full": "Северо-Западный",
                    "slp": 1015.2,
                    "dni": 0,
                    "dewpt": 5.7,
                    "snow": 0,
                    "uv": 0,
                    "wind_dir": 324,
                    "clouds_hi": 0,
                    "precip": 0,
                    "vis": 24.1349,
                    "dhi": 0.24,
                    "app_temp": 9.6,
                    "datetime": "2020-03-03:18",
                    "temp": 9.6,
                    "ghi": 0,
                    "clouds_mid": 0,
                    "clouds_low": 49
                },
                {
                    "wind_cdir": "СЗ",
                    "rh": 80,
                    "pod": "n",
                    "timestamp_utc": "2020-03-03T19:00:00",
                    "pres": 948.074,
                    "solar_rad": 0,
                    "ozone": 305.867,
                    "weather": {
                        "icon": "c02n",
                        "code": 802,
                        "description": "Местами облачно"
                    },
                    "wind_gust_spd": 16.384,
                    "timestamp_local": "2020-03-03T20:00:00",
                    "snow_depth": 0,
                    "clouds": 49,
                    "ts": 1583262000,
                    "wind_spd": 6.10586,
                    "pop": 0,
                    "wind_cdir_full": "Северо-Западный",
                    "slp": 1016.69,
                    "dni": 0,
                    "dewpt": 5.6,
                    "snow": 0,
                    "uv": 0,
                    "wind_dir": 326,
                    "clouds_hi": 0,
                    "precip": 0,
                    "vis": 24.1348,
                    "dhi": 0,
                    "app_temp": 8.7,
                    "datetime": "2020-03-03:19",
                    "temp": 8.7,
                    "ghi": 0,
                    "clouds_mid": 1,
                    "clouds_low": 49
                },
                {
                    "wind_cdir": "СЗ",
                    "rh": 83,
                    "pod": "n",
                    "timestamp_utc": "2020-03-03T20:00:00",
                    "pres": 948.708,
                    "solar_rad": 0,
                    "ozone": 304.417,
                    "weather": {
                        "icon": "c02n",
                        "code": 802,
                        "description": "Местами облачно"
                    },
                    "wind_gust_spd": 15.7345,
                    "timestamp_local": "2020-03-03T21:00:00",
                    "snow_depth": 0,
                    "clouds": 50,
                    "ts": 1583265600,
                    "wind_spd": 4.36325,
                    "pop": 0,
                    "wind_cdir_full": "Северо-Западный",
                    "slp": 1017.45,
                    "dni": 0,
                    "dewpt": 5.7,
                    "snow": 0,
                    "uv": 0,
                    "wind_dir": 324,
                    "clouds_hi": 1,
                    "precip": 0,
                    "vis": 24.135,
                    "dhi": 0,
                    "app_temp": 8.2,
                    "datetime": "2020-03-03:20",
                    "temp": 8.2,
                    "ghi": 0,
                    "clouds_mid": 9,
                    "clouds_low": 45
                },
                {
                    "wind_cdir": "СЗ",
                    "rh": 84,
                    "pod": "n",
                    "timestamp_utc": "2020-03-03T21:00:00",
                    "pres": 949.95,
                    "solar_rad": 0,
                    "ozone": 302.318,
                    "weather": {
                        "icon": "c02n",
                        "code": 802,
                        "description": "Местами облачно"
                    },
                    "wind_gust_spd": 14.8906,
                    "timestamp_local": "2020-03-03T22:00:00",
                    "snow_depth": 0,
                    "clouds": 50,
                    "ts": 1583269200,
                    "wind_spd": 3.03518,
                    "pop": 0,
                    "wind_cdir_full": "Северо-Западный",
                    "slp": 1018.82,
                    "dni": 0,
                    "dewpt": 5.5,
                    "snow": 0,
                    "uv": 0,
                    "wind_dir": 320,
                    "clouds_hi": 0,
                    "precip": 0,
                    "vis": 24.1352,
                    "dhi": 0,
                    "app_temp": 7.8,
                    "datetime": "2020-03-03:21",
                    "temp": 7.8,
                    "ghi": 0,
                    "clouds_mid": 18,
                    "clouds_low": 41
                },
                {
                    "wind_cdir": "ЗСЗ",
                    "rh": 86,
                    "pod": "n",
                    "timestamp_utc": "2020-03-03T22:00:00",
                    "pres": 950.653,
                    "solar_rad": 0,
                    "ozone": 302.986,
                    "weather": {
                        "icon": "c02n",
                        "code": 802,
                        "description": "Местами облачно"
                    },
                    "wind_gust_spd": 11.965,
                    "timestamp_local": "2020-03-03T23:00:00",
                    "snow_depth": 0,
                    "clouds": 68,
                    "ts": 1583272800,
                    "wind_spd": 1.46299,
                    "pop": 0,
                    "wind_cdir_full": "Западный-Северо-Западный",
                    "slp": 1019.67,
                    "dni": 0,
                    "dewpt": 5.4,
                    "snow": 0,
                    "uv": 0,
                    "wind_dir": 295,
                    "clouds_hi": 0,
                    "precip": 0,
                    "vis": 24.135,
                    "dhi": 0,
                    "app_temp": 7.5,
                    "datetime": "2020-03-03:22",
                    "temp": 7.5,
                    "ghi": 0,
                    "clouds_mid": 42,
                    "clouds_low": 44
                },
                {
                    "wind_cdir": "ЗСЗ",
                    "rh": 83,
                    "pod": "n",
                    "timestamp_utc": "2020-03-03T23:00:00",
                    "pres": 950.209,
                    "solar_rad": 0,
                    "ozone": 301.992,
                    "weather": {
                        "icon": "c02n",
                        "code": 802,
                        "description": "Местами облачно"
                    },
                    "wind_gust_spd": 9.15826,
                    "timestamp_local": "2020-03-04T00:00:00",
                    "snow_depth": 0,
                    "clouds": 58,
                    "ts": 1583276400,
                    "wind_spd": 0.457501,
                    "pop": 0,
                    "wind_cdir_full": "Западный-Северо-Западный",
                    "slp": 1019.28,
                    "dni": 0,
                    "dewpt": 4.9,
                    "snow": 0,
                    "uv": 0,
                    "wind_dir": 301,
                    "clouds_hi": 0,
                    "precip": 0,
                    "vis": 24.1353,
                    "dhi": 0,
                    "app_temp": 7.4,
                    "datetime": "2020-03-03:23",
                    "temp": 7.4,
                    "ghi": 0,
                    "clouds_mid": 44,
                    "clouds_low": 20
                },
                {
                    "wind_cdir": "ЗЮЗ",
                    "rh": 82,
                    "pod": "n",
                    "timestamp_utc": "2020-03-04T00:00:00",
                    "pres": 949.992,
                    "solar_rad": 0,
                    "ozone": 298.809,
                    "weather": {
                        "icon": "c02n",
                        "code": 802,
                        "description": "Местами облачно"
                    },
                    "wind_gust_spd": 6.39106,
                    "timestamp_local": "2020-03-04T01:00:00",
                    "snow_depth": 0,
                    "clouds": 51,
                    "ts": 1583280000,
                    "wind_spd": 1.11824,
                    "pop": 0,
                    "wind_cdir_full": "Западный-Юго-Западный",
                    "slp": 1019.13,
                    "dni": 0,
                    "dewpt": 4.7,
                    "snow": 0,
                    "uv": 0,
                    "wind_dir": 246,
                    "clouds_hi": 0,
                    "precip": 0,
                    "vis": 24.1351,
                    "dhi": 0,
                    "app_temp": 4.1,
                    "datetime": "2020-03-04:00",
                    "temp": 7.2,
                    "ghi": 0,
                    "clouds_mid": 49,
                    "clouds_low": 3
                },
                {
                    "wind_cdir": "ЮЗ",
                    "rh": 85,
                    "pod": "n",
                    "timestamp_utc": "2020-03-04T01:00:00",
                    "pres": 949.739,
                    "solar_rad": 0,
                    "ozone": 298.6,
                    "weather": {
                        "icon": "c02n",
                        "code": 801,
                        "description": "Преимущественно ясно"
                    },
                    "wind_gust_spd": 6.18677,
                    "timestamp_local": "2020-03-04T02:00:00",
                    "snow_depth": 0,
                    "clouds": 24,
                    "ts": 1583283600,
                    "wind_spd": 1.48667,
                    "pop": 0,
                    "wind_cdir_full": "Юго-Западный",
                    "slp": 1019.09,
                    "dni": 0,
                    "dewpt": 4.4,
                    "snow": 0,
                    "uv": 0,
                    "wind_dir": 217,
                    "clouds_hi": 0,
                    "precip": 0,
                    "vis": 24.135,
                    "dhi": 0,
                    "app_temp": 3.3,
                    "datetime": "2020-03-04:01",
                    "temp": 6.6,
                    "ghi": 0,
                    "clouds_mid": 24,
                    "clouds_low": 0
                },
                {
                    "wind_cdir": "ЮЮЗ",
                    "rh": 85,
                    "pod": "n",
                    "timestamp_utc": "2020-03-04T02:00:00",
                    "pres": 949.655,
                    "solar_rad": 0,
                    "ozone": 295.849,
                    "weather": {
                        "icon": "c02n",
                        "code": 802,
                        "description": "Местами облачно"
                    },
                    "wind_gust_spd": 5.79573,
                    "timestamp_local": "2020-03-04T03:00:00",
                    "snow_depth": 0,
                    "clouds": 43,
                    "ts": 1583287200,
                    "wind_spd": 1.30323,
                    "pop": 0,
                    "wind_cdir_full": "Юго-Юго-Западный",
                    "slp": 1019.14,
                    "dni": 0,
                    "dewpt": 4.1,
                    "snow": 0,
                    "uv": 0,
                    "wind_dir": 212,
                    "clouds_hi": 0,
                    "precip": 0,
                    "vis": 24.1348,
                    "dhi": 0,
                    "app_temp": 2.9,
                    "datetime": "2020-03-04:02",
                    "temp": 6.3,
                    "ghi": 0,
                    "clouds_mid": 43,
                    "clouds_low": 0
                },
                {
                    "wind_cdir": "ЮЗ",
                    "rh": 80,
                    "pod": "n",
                    "timestamp_utc": "2020-03-04T03:00:00",
                    "pres": 949.138,
                    "solar_rad": 0,
                    "ozone": 294.022,
                    "weather": {
                        "icon": "c02n",
                        "code": 802,
                        "description": "Местами облачно"
                    },
                    "wind_gust_spd": 4.16767,
                    "timestamp_local": "2020-03-04T04:00:00",
                    "snow_depth": 0,
                    "clouds": 61,
                    "ts": 1583290800,
                    "wind_spd": 1.1992,
                    "pop": 15,
                    "wind_cdir_full": "Юго-Западный",
                    "slp": 1018.52,
                    "dni": 0,
                    "dewpt": 3.9,
                    "snow": 0,
                    "uv": 0,
                    "wind_dir": 218,
                    "clouds_hi": 0,
                    "precip": 0.00390625,
                    "vis": 24.135,
                    "dhi": 0,
                    "app_temp": 3.4,
                    "datetime": "2020-03-04:03",
                    "temp": 6.7,
                    "ghi": 0,
                    "clouds_mid": 61,
                    "clouds_low": 0
                },
                {
                    "wind_cdir": "ЮЗ",
                    "rh": 77,
                    "pod": "n",
                    "timestamp_utc": "2020-03-04T04:00:00",
                    "pres": 948.858,
                    "solar_rad": 0,
                    "ozone": 292.977,
                    "weather": {
                        "icon": "c04n",
                        "code": 803,
                        "description": "Облачно с прояснениями"
                    },
                    "wind_gust_spd": 3.49124,
                    "timestamp_local": "2020-03-04T05:00:00",
                    "snow_depth": 0,
                    "clouds": 89,
                    "ts": 1583294400,
                    "wind_spd": 1.13794,
                    "pop": 0,
                    "wind_cdir_full": "Юго-Западный",
                    "slp": 1018.12,
                    "dni": 0,
                    "dewpt": 3.8,
                    "snow": 0,
                    "uv": 0,
                    "wind_dir": 214,
                    "clouds_hi": 0,
                    "precip": 0,
                    "vis": 24.1351,
                    "dhi": 0,
                    "app_temp": 4,
                    "datetime": "2020-03-04:04",
                    "temp": 7.2,
                    "ghi": 0,
                    "clouds_mid": 82,
                    "clouds_low": 59
                },
                {
                    "wind_cdir": "ЮЮЗ",
                    "rh": 79,
                    "pod": "n",
                    "timestamp_utc": "2020-03-04T05:00:00",
                    "pres": 948.713,
                    "solar_rad": 0,
                    "ozone": 291.902,
                    "weather": {
                        "icon": "r01n",
                        "code": 500,
                        "description": "Небольшой дождь"
                    },
                    "wind_gust_spd": 4.71859,
                    "timestamp_local": "2020-03-04T06:00:00",
                    "snow_depth": 0,
                    "clouds": 94,
                    "ts": 1583298000,
                    "wind_spd": 1.01131,
                    "pop": 10,
                    "wind_cdir_full": "Юго-Юго-Западный",
                    "slp": 1018.01,
                    "dni": 0,
                    "dewpt": 3.9,
                    "snow": 0,
                    "uv": 0,
                    "wind_dir": 212,
                    "clouds_hi": 0,
                    "precip": 0.12109375,
                    "vis": 24.1352,
                    "dhi": 0,
                    "app_temp": 4.1,
                    "datetime": "2020-03-04:05",
                    "temp": 7.2,
                    "ghi": 0,
                    "clouds_mid": 91,
                    "clouds_low": 71
                },
                {
                    "wind_cdir": "ЮЮЗ",
                    "rh": 78,
                    "pod": "n",
                    "timestamp_utc": "2020-03-04T06:00:00",
                    "pres": 948.412,
                    "solar_rad": 0,
                    "ozone": 290.433,
                    "weather": {
                        "icon": "r01n",
                        "code": 500,
                        "description": "Небольшой дождь"
                    },
                    "wind_gust_spd": 7.86509,
                    "timestamp_local": "2020-03-04T07:00:00",
                    "snow_depth": 0,
                    "clouds": 98,
                    "ts": 1583301600,
                    "wind_spd": 1.72281,
                    "pop": 25,
                    "wind_cdir_full": "Юго-Юго-Западный",
                    "slp": 1017.64,
                    "dni": 0,
                    "dewpt": 4.3,
                    "snow": 0,
                    "uv": 0,
                    "wind_dir": 200,
                    "clouds_hi": 78,
                    "precip": 0.33984375,
                    "vis": 24.1349,
                    "dhi": 0,
                    "app_temp": 7.5,
                    "datetime": "2020-03-04:06",
                    "temp": 7.5,
                    "ghi": 0,
                    "clouds_mid": 85,
                    "clouds_low": 61
                },
                {
                    "wind_cdir": "З",
                    "rh": 82,
                    "pod": "d",
                    "timestamp_utc": "2020-03-04T07:00:00",
                    "pres": 948.586,
                    "solar_rad": 11.5019,
                    "ozone": 290.003,
                    "weather": {
                        "icon": "r01d",
                        "code": 500,
                        "description": "Небольшой дождь"
                    },
                    "wind_gust_spd": 7.80023,
                    "timestamp_local": "2020-03-04T08:00:00",
                    "snow_depth": 0,
                    "clouds": 89,
                    "ts": 1583305200,
                    "wind_spd": 0.436178,
                    "pop": 15,
                    "wind_cdir_full": "Западный",
                    "slp": 1017.76,
                    "dni": 189.87,
                    "dewpt": 4.9,
                    "snow": 0,
                    "uv": 0.839333,
                    "wind_dir": 261,
                    "clouds_hi": 2,
                    "precip": 0.171875,
                    "vis": 24.135,
                    "dhi": 24.84,
                    "app_temp": 7.6,
                    "datetime": "2020-03-04:07",
                    "temp": 7.6,
                    "ghi": 25.28,
                    "clouds_mid": 79,
                    "clouds_low": 72
                },
                {
                    "wind_cdir": "ЮЮЗ",
                    "rh": 83,
                    "pod": "d",
                    "timestamp_utc": "2020-03-04T08:00:00",
                    "pres": 949.356,
                    "solar_rad": 112.049,
                    "ozone": 288.462,
                    "weather": {
                        "icon": "r01d",
                        "code": 500,
                        "description": "Небольшой дождь"
                    },
                    "wind_gust_spd": 7.81566,
                    "timestamp_local": "2020-03-04T09:00:00",
                    "snow_depth": 0,
                    "clouds": 82,
                    "ts": 1583308800,
                    "wind_spd": 0.84974,
                    "pop": 10,
                    "wind_cdir_full": "Юго-Юго-Западный",
                    "slp": 1018.44,
                    "dni": 577,
                    "dewpt": 5.5,
                    "snow": 0,
                    "uv": 1.01801,
                    "wind_dir": 207,
                    "clouds_hi": 6,
                    "precip": 0.140625,
                    "vis": 24.135,
                    "dhi": 63.48,
                    "app_temp": 8.3,
                    "datetime": "2020-03-04:08",
                    "temp": 8.3,
                    "ghi": 190.73,
                    "clouds_mid": 74,
                    "clouds_low": 75
                }
            ],
            "city_name": "Autol",
            "lon": "-2.00525",
            "timezone": "Europe/Madrid",
            "lat": "42.21661",
            "country_code": "ES",
            "state_code": "27"
        }
    """.trimIndent()

    private val jsonDaily = """
        {
            "data": [
                {
                    "moonrise_ts": 1583221175,
                    "wind_cdir": "ЮЮВ",
                    "rh": 84,
                    "pres": 993.665,
                    "high_temp": 4.8,
                    "sunset_ts": 1583248366,
                    "ozone": 398.903,
                    "moon_phase": 0.624447,
                    "wind_gust_spd": 8.7742,
                    "snow_depth": 0,
                    "clouds": 100,
                    "ts": 1583182860,
                    "sunrise_ts": 1583208839,
                    "app_min_temp": -4,
                    "wind_spd": 2.25132,
                    "pop": 60,
                    "wind_cdir_full": "Юго-Юго-Восточный",
                    "slp": 1011.7,
                    "valid_date": "2020-03-03",
                    "app_max_temp": 1.1,
                    "vis": 0,
                    "dewpt": 0.6,
                    "snow": 0,
                    "uv": 1.34565,
                    "weather": {
                        "icon": "c04d",
                        "code": 804,
                        "description": "Облачно"
                    },
                    "wind_dir": 152,
                    "max_dhi": null,
                    "clouds_hi": 86,
                    "precip": 1.40234,
                    "low_temp": 2.4,
                    "max_temp": 4.8,
                    "moonset_ts": 1583197163,
                    "datetime": "2020-03-03",
                    "temp": 3,
                    "min_temp": 0.7,
                    "clouds_mid": 91,
                    "clouds_low": 78
                },
                {
                    "moonrise_ts": 1583309980,
                    "wind_cdir": "ЮВ",
                    "rh": 84,
                    "pres": 998.378,
                    "high_temp": 8.5,
                    "sunset_ts": 1583334887,
                    "ozone": 401.432,
                    "moon_phase": 0.728785,
                    "wind_gust_spd": 8.95387,
                    "snow_depth": 0,
                    "clouds": 95,
                    "ts": 1583269260,
                    "sunrise_ts": 1583295092,
                    "app_min_temp": -2.4,
                    "wind_spd": 1.76377,
                    "pop": 20,
                    "wind_cdir_full": "Юго-Восточный",
                    "slp": 1016.37,
                    "valid_date": "2020-03-04",
                    "app_max_temp": 8.5,
                    "vis": 0,
                    "dewpt": 2.2,
                    "snow": 0,
                    "uv": 1.60992,
                    "weather": {
                        "icon": "c04d",
                        "code": 804,
                        "description": "Облачно"
                    },
                    "wind_dir": 145,
                    "max_dhi": null,
                    "clouds_hi": 33,
                    "precip": 0.226562,
                    "low_temp": 2,
                    "max_temp": 8.5,
                    "moonset_ts": 1583287275,
                    "datetime": "2020-03-04",
                    "temp": 4.8,
                    "min_temp": 2,
                    "clouds_mid": 38,
                    "clouds_low": 80
                },
                {
                    "moonrise_ts": 1583399637,
                    "wind_cdir": "ЮВ",
                    "rh": 86,
                    "pres": 995.633,
                    "high_temp": 9.2,
                    "sunset_ts": 1583421408,
                    "ozone": 402.133,
                    "moon_phase": 0.824401,
                    "wind_gust_spd": 14.4225,
                    "snow_depth": 0,
                    "clouds": 100,
                    "ts": 1583355660,
                    "sunrise_ts": 1583381344,
                    "app_min_temp": -0.9,
                    "wind_spd": 4.54901,
                    "pop": 65,
                    "wind_cdir_full": "Юго-Восточный",
                    "slp": 1013.49,
                    "valid_date": "2020-03-05",
                    "app_max_temp": 9.2,
                    "vis": 0,
                    "dewpt": 3.7,
                    "snow": 0,
                    "uv": 1.36642,
                    "weather": {
                        "icon": "c04d",
                        "code": 804,
                        "description": "Облачно"
                    },
                    "wind_dir": 137,
                    "max_dhi": null,
                    "clouds_hi": 87,
                    "precip": 1.98828,
                    "low_temp": 3.5,
                    "max_temp": 9.2,
                    "moonset_ts": 1583376736,
                    "datetime": "2020-03-05",
                    "temp": 6,
                    "min_temp": 3.2,
                    "clouds_mid": 89,
                    "clouds_low": 63
                },
                {
                    "moonrise_ts": 1583490216,
                    "wind_cdir": "Ю",
                    "rh": 86,
                    "pres": 990.179,
                    "high_temp": 8.8,
                    "sunset_ts": 1583507929,
                    "ozone": 343.377,
                    "moon_phase": 0.904575,
                    "wind_gust_spd": 14.3421,
                    "snow_depth": 0,
                    "clouds": 98,
                    "ts": 1583442060,
                    "sunrise_ts": 1583467596,
                    "app_min_temp": 1.1,
                    "wind_spd": 4.06225,
                    "pop": 10,
                    "wind_cdir_full": "Южный",
                    "slp": 1010.32,
                    "valid_date": "2020-03-06",
                    "app_max_temp": 8.8,
                    "vis": 24.135,
                    "dewpt": 4.1,
                    "snow": 0,
                    "uv": 1.03247,
                    "weather": {
                        "icon": "c04d",
                        "code": 804,
                        "description": "Облачно"
                    },
                    "wind_dir": 169,
                    "max_dhi": null,
                    "clouds_hi": 76,
                    "precip": 0.125,
                    "low_temp": 3.6,
                    "max_temp": 8.8,
                    "moonset_ts": 1583465510,
                    "datetime": "2020-03-06",
                    "temp": 6.4,
                    "min_temp": 4.7,
                    "clouds_mid": 97,
                    "clouds_low": 47
                },
                {
                    "moonrise_ts": 1583581554,
                    "wind_cdir": "ЮЮВ",
                    "rh": 91,
                    "pres": 990.567,
                    "high_temp": 9.4,
                    "sunset_ts": 1583594449,
                    "ozone": 337.104,
                    "moon_phase": 0.962861,
                    "wind_gust_spd": 11.4064,
                    "snow_depth": 0,
                    "clouds": 92,
                    "ts": 1583528460,
                    "sunrise_ts": 1583553847,
                    "app_min_temp": -0.4,
                    "wind_spd": 3.7174,
                    "pop": 65,
                    "wind_cdir_full": "Юго-Юго-Восточный",
                    "slp": 1010.76,
                    "valid_date": "2020-03-07",
                    "app_max_temp": 8.6,
                    "vis": 23.8501,
                    "dewpt": 4.7,
                    "snow": 0,
                    "uv": 1.03336,
                    "weather": {
                        "icon": "c04d",
                        "code": 804,
                        "description": "Облачно"
                    },
                    "wind_dir": 168,
                    "max_dhi": null,
                    "clouds_hi": 43,
                    "precip": 1.8125,
                    "low_temp": 4.1,
                    "max_temp": 8.7,
                    "moonset_ts": 1583553718,
                    "datetime": "2020-03-07",
                    "temp": 6,
                    "min_temp": 3.6,
                    "clouds_mid": 79,
                    "clouds_low": 66
                },
                {
                    "moonrise_ts": 1583673342,
                    "wind_cdir": "Ю",
                    "rh": 88,
                    "pres": 992.662,
                    "high_temp": 12.2,
                    "sunset_ts": 1583680969,
                    "ozone": 334.274,
                    "moon_phase": 0.993978,
                    "wind_gust_spd": 9.50384,
                    "snow_depth": 0,
                    "clouds": 90,
                    "ts": 1583614860,
                    "sunrise_ts": 1583640097,
                    "app_min_temp": 1.6,
                    "wind_spd": 3.03536,
                    "pop": 10,
                    "wind_cdir_full": "Южный",
                    "slp": 1012.87,
                    "valid_date": "2020-03-08",
                    "app_max_temp": 11.8,
                    "vis": 24.135,
                    "dewpt": 5.5,
                    "snow": 0,
                    "uv": 1.68595,
                    "weather": {
                        "icon": "c04d",
                        "code": 804,
                        "description": "Облачно"
                    },
                    "wind_dir": 180,
                    "max_dhi": null,
                    "clouds_hi": 44,
                    "precip": 0.125,
                    "low_temp": 6.4,
                    "max_temp": 11.8,
                    "moonset_ts": 1583641536,
                    "datetime": "2020-03-08",
                    "temp": 7.5,
                    "min_temp": 5,
                    "clouds_mid": 73,
                    "clouds_low": 46
                },
                {
                    "moonrise_ts": 1583765302,
                    "wind_cdir": "ЮВ",
                    "rh": 79,
                    "pres": 993.2,
                    "high_temp": 8,
                    "sunset_ts": 1583767489,
                    "ozone": 332.851,
                    "moon_phase": 0.994761,
                    "wind_gust_spd": 14.2138,
                    "snow_depth": 0,
                    "clouds": 100,
                    "ts": 1583701260,
                    "sunrise_ts": 1583726347,
                    "app_min_temp": 3.1,
                    "wind_spd": 4.44244,
                    "pop": 15,
                    "wind_cdir_full": "Юго-Восточный",
                    "slp": 1013.24,
                    "valid_date": "2020-03-09",
                    "app_max_temp": 12.2,
                    "vis": 24.1352,
                    "dewpt": 4.9,
                    "snow": 0,
                    "uv": 1.05602,
                    "weather": {
                        "icon": "c04d",
                        "code": 804,
                        "description": "Облачно"
                    },
                    "wind_dir": 146,
                    "max_dhi": null,
                    "clouds_hi": 100,
                    "precip": 0.1875,
                    "low_temp": 5.3,
                    "max_temp": 12.2,
                    "moonset_ts": 1583729117,
                    "datetime": "2020-03-09",
                    "temp": 8.5,
                    "min_temp": 6.3,
                    "clouds_mid": 38,
                    "clouds_low": 20
                },
                {
                    "moonrise_ts": 1583857271,
                    "wind_cdir": "ЮЮЗ",
                    "rh": 69,
                    "pres": 992.536,
                    "high_temp": 6,
                    "sunset_ts": 1583854008,
                    "ozone": 373.131,
                    "moon_phase": 0.964876,
                    "wind_gust_spd": 12.5161,
                    "snow_depth": 0,
                    "clouds": 77,
                    "ts": 1583787660,
                    "sunrise_ts": 1583812597,
                    "app_min_temp": 0.7,
                    "wind_spd": 4.86274,
                    "pop": 0,
                    "wind_cdir_full": "Юго-Юго-Западный",
                    "slp": 1012.81,
                    "valid_date": "2020-03-10",
                    "app_max_temp": 3.6,
                    "vis": 24.135,
                    "dewpt": 0.7,
                    "snow": 0,
                    "uv": 2.85991,
                    "weather": {
                        "icon": "c04d",
                        "code": 804,
                        "description": "Облачно"
                    },
                    "wind_dir": 195,
                    "max_dhi": null,
                    "clouds_hi": 23,
                    "precip": 0,
                    "low_temp": 1.3,
                    "max_temp": 8,
                    "moonset_ts": 1583816585,
                    "datetime": "2020-03-10",
                    "temp": 6,
                    "min_temp": 3.7,
                    "clouds_mid": 25,
                    "clouds_low": 55
                },
                {
                    "moonrise_ts": 1583943671,
                    "wind_cdir": "ЮЗ",
                    "rh": 67,
                    "pres": 998.917,
                    "high_temp": 5.5,
                    "sunset_ts": 1583940528,
                    "ozone": 409.125,
                    "moon_phase": 0.906955,
                    "wind_gust_spd": 10.341,
                    "snow_depth": 0,
                    "clouds": 25,
                    "ts": 1583874060,
                    "sunrise_ts": 1583898846,
                    "app_min_temp": -3.3,
                    "wind_spd": 3.6264,
                    "pop": 0,
                    "wind_cdir_full": "Юго-Западный",
                    "slp": 1019.66,
                    "valid_date": "2020-03-11",
                    "app_max_temp": 2.6,
                    "vis": 24.135,
                    "dewpt": -2.2,
                    "snow": 0,
                    "uv": 2.6359,
                    "weather": {
                        "icon": "c02d",
                        "code": 802,
                        "description": "Местами облачно"
                    },
                    "wind_dir": 219,
                    "max_dhi": null,
                    "clouds_hi": 0,
                    "precip": 0,
                    "low_temp": 2.3,
                    "max_temp": 6.2,
                    "moonset_ts": 1583904038,
                    "datetime": "2020-03-11",
                    "temp": 3.7,
                    "min_temp": 1,
                    "clouds_mid": 0,
                    "clouds_low": 25
                },
                {
                    "moonrise_ts": 1584035583,
                    "wind_cdir": "ЮЮЗ",
                    "rh": 74,
                    "pres": 996.349,
                    "high_temp": 8.4,
                    "sunset_ts": 1584027047,
                    "ozone": 361.503,
                    "moon_phase": 0.826081,
                    "wind_gust_spd": 13.7204,
                    "snow_depth": 0,
                    "clouds": 66,
                    "ts": 1583960460,
                    "sunrise_ts": 1583985095,
                    "app_min_temp": -2,
                    "wind_spd": 5.1983,
                    "pop": 15,
                    "wind_cdir_full": "Юго-Юго-Западный",
                    "slp": 1017.04,
                    "valid_date": "2020-03-12",
                    "app_max_temp": 1.9,
                    "vis": 24.135,
                    "dewpt": -0.4,
                    "snow": 0,
                    "uv": 1.24794,
                    "weather": {
                        "icon": "c03d",
                        "code": 803,
                        "description": "Облачно с прояснениями"
                    },
                    "wind_dir": 213,
                    "max_dhi": null,
                    "clouds_hi": 45,
                    "precip": 0.1875,
                    "low_temp": 0.9,
                    "max_temp": 5.5,
                    "moonset_ts": 1583991576,
                    "datetime": "2020-03-12",
                    "temp": 3.9,
                    "min_temp": 2.3,
                    "clouds_mid": 41,
                    "clouds_low": 52
                },
                {
                    "moonrise_ts": 1584127416,
                    "wind_cdir": "ЮЗ",
                    "rh": 84,
                    "pres": 993.611,
                    "high_temp": 7.8,
                    "sunset_ts": 1584113566,
                    "ozone": 357.991,
                    "moon_phase": 0.728809,
                    "wind_gust_spd": 7.51615,
                    "snow_depth": 0,
                    "clouds": 100,
                    "ts": 1584046860,
                    "sunrise_ts": 1584071344,
                    "app_min_temp": -1.1,
                    "wind_spd": 3.14936,
                    "pop": 65,
                    "wind_cdir_full": "Юго-Западный",
                    "slp": 1014.26,
                    "valid_date": "2020-03-13",
                    "app_max_temp": 2.3,
                    "vis": 22.9158,
                    "dewpt": 1.5,
                    "snow": 0,
                    "uv": 0.878053,
                    "weather": {
                        "icon": "c04d",
                        "code": 804,
                        "description": "Облачно"
                    },
                    "wind_dir": 234,
                    "max_dhi": null,
                    "clouds_hi": 68,
                    "precip": 1.75,
                    "low_temp": 0.6,
                    "max_temp": 5.8,
                    "moonset_ts": 1584079305,
                    "datetime": "2020-03-13",
                    "temp": 4.1,
                    "min_temp": 0.9,
                    "clouds_mid": 98,
                    "clouds_low": 51
                },
                {
                    "moonrise_ts": 1584219129,
                    "wind_cdir": "З",
                    "rh": 62,
                    "pres": 997.58,
                    "high_temp": 7.8,
                    "sunset_ts": 1584200084,
                    "ozone": 420.146,
                    "moon_phase": 0.622061,
                    "wind_gust_spd": 10.8292,
                    "snow_depth": 0,
                    "clouds": 22,
                    "ts": 1584133260,
                    "sunrise_ts": 1584157592,
                    "app_min_temp": -3.8,
                    "wind_spd": 4.68894,
                    "pop": 0,
                    "wind_cdir_full": "Западный",
                    "slp": 1018.39,
                    "valid_date": "2020-03-14",
                    "app_max_temp": 2.9,
                    "vis": 24.1349,
                    "dewpt": -3.4,
                    "snow": 0,
                    "uv": 1.94757,
                    "weather": {
                        "icon": "c02d",
                        "code": 802,
                        "description": "Местами облачно"
                    },
                    "wind_dir": 269,
                    "max_dhi": null,
                    "clouds_hi": 0,
                    "precip": 0,
                    "low_temp": 2.3,
                    "max_temp": 6.2,
                    "moonset_ts": 1584167361,
                    "datetime": "2020-03-14",
                    "temp": 3.6,
                    "min_temp": 0.9,
                    "clouds_mid": 0,
                    "clouds_low": 22
                },
                {
                    "moonrise_ts": 1584224217,
                    "wind_cdir": "ЮЗ",
                    "rh": 65,
                    "pres": 1003.46,
                    "high_temp": 10.2,
                    "sunset_ts": 1584286603,
                    "ozone": 405.396,
                    "moon_phase": 0.51224,
                    "wind_gust_spd": 13.2068,
                    "snow_depth": 0,
                    "clouds": 48,
                    "ts": 1584219660,
                    "sunrise_ts": 1584243840,
                    "app_min_temp": -3.4,
                    "wind_spd": 5.34041,
                    "pop": 0,
                    "wind_cdir_full": "Юго-Западный",
                    "slp": 1024.33,
                    "valid_date": "2020-03-15",
                    "app_max_temp": 8.4,
                    "vis": 24.1349,
                    "dewpt": -1.6,
                    "snow": 0,
                    "uv": 0.972602,
                    "weather": {
                        "icon": "c03d",
                        "code": 803,
                        "description": "Облачно с прояснениями"
                    },
                    "wind_dir": 215,
                    "max_dhi": null,
                    "clouds_hi": 45,
                    "precip": 0,
                    "low_temp": 4.5,
                    "max_temp": 8.4,
                    "moonset_ts": 1584255896,
                    "datetime": "2020-03-15",
                    "temp": 4.8,
                    "min_temp": 1.2,
                    "clouds_mid": 34,
                    "clouds_low": 0
                },
                {
                    "moonrise_ts": 1584315293,
                    "wind_cdir": "ЗСЗ",
                    "rh": 65,
                    "pres": 998.759,
                    "high_temp": 4.2,
                    "sunset_ts": 1584373121,
                    "ozone": 427.335,
                    "moon_phase": 0.404782,
                    "wind_gust_spd": 14.5008,
                    "snow_depth": 0,
                    "clouds": 75,
                    "ts": 1584306060,
                    "sunrise_ts": 1584330088,
                    "app_min_temp": -0.1,
                    "wind_spd": 6.843,
                    "pop": 10,
                    "wind_cdir_full": "Западный-Северо-Западный",
                    "slp": 1019.43,
                    "valid_date": "2020-03-16",
                    "app_max_temp": 7.8,
                    "vis": 23.2739,
                    "dewpt": -0.5,
                    "snow": 0,
                    "uv": 1.86173,
                    "weather": {
                        "icon": "c04d",
                        "code": 804,
                        "description": "Облачно"
                    },
                    "wind_dir": 282,
                    "max_dhi": null,
                    "clouds_hi": 64,
                    "precip": 0.125,
                    "low_temp": 0.5,
                    "max_temp": 7.8,
                    "moonset_ts": 1584345042,
                    "datetime": "2020-03-16",
                    "temp": 5.8,
                    "min_temp": 0.5,
                    "clouds_mid": 66,
                    "clouds_low": 57
                },
                {
                    "moonrise_ts": 1584405731,
                    "wind_cdir": "СЗ",
                    "rh": 54,
                    "pres": 1010.32,
                    "high_temp": 7.8,
                    "sunset_ts": 1584459639,
                    "ozone": 370.753,
                    "moon_phase": 0.304133,
                    "wind_gust_spd": 8.71166,
                    "snow_depth": 0,
                    "clouds": 6,
                    "ts": 1584392460,
                    "sunrise_ts": 1584416336,
                    "app_min_temp": -4.2,
                    "wind_spd": 3.74111,
                    "pop": 0,
                    "wind_cdir_full": "Северо-Западный",
                    "slp": 1031.26,
                    "valid_date": "2020-03-17",
                    "app_max_temp": 7.8,
                    "vis": 24.1353,
                    "dewpt": -4.7,
                    "snow": 0,
                    "uv": 2.9989,
                    "weather": {
                        "icon": "c02d",
                        "code": 801,
                        "description": "Преимущественно ясно"
                    },
                    "wind_dir": 314,
                    "max_dhi": null,
                    "clouds_hi": 0,
                    "precip": 0,
                    "low_temp": 1.5,
                    "max_temp": 7.8,
                    "moonset_ts": 1584434823,
                    "datetime": "2020-03-17",
                    "temp": 4.2,
                    "min_temp": 0.6,
                    "clouds_mid": 0,
                    "clouds_low": 6
                },
                {
                    "moonrise_ts": 1584495380,
                    "wind_cdir": "ЗЮЗ",
                    "rh": 50,
                    "pres": 1006.57,
                    "high_temp": 10.2,
                    "sunset_ts": 1584546157,
                    "ozone": 362.974,
                    "moon_phase": 0.213914,
                    "wind_gust_spd": 7.23817,
                    "snow_depth": 0,
                    "clouds": 0,
                    "ts": 1584478860,
                    "sunrise_ts": 1584502583,
                    "app_min_temp": -2,
                    "wind_spd": 2.97799,
                    "pop": 0,
                    "wind_cdir_full": "Западный-Юго-Западный",
                    "slp": 1027.3,
                    "valid_date": "2020-03-18",
                    "app_max_temp": 10.2,
                    "vis": 24.135,
                    "dewpt": -3.8,
                    "snow": 0,
                    "uv": 3.03178,
                    "weather": {
                        "icon": "c01d",
                        "code": 800,
                        "description": "Ясно"
                    },
                    "wind_dir": 251,
                    "max_dhi": null,
                    "clouds_hi": 0,
                    "precip": 0,
                    "low_temp": 3.7,
                    "max_temp": 10.2,
                    "moonset_ts": 1584525110,
                    "datetime": "2020-03-18",
                    "temp": 6.2,
                    "min_temp": 2.3,
                    "clouds_mid": 0,
                    "clouds_low": 0
                }
            ],
            "city_name": "Mosco",
            "lon": "37.61556",
            "timezone": "Europe/Moscow",
            "lat": "55.75222",
            "country_code": "RU",
            "state_code": "48"
        }
    """.trimIndent()

    private val jsonCurrent = """
        {
            "data": [
                {
                    "rh": 77,
                    "pod": "d",
                    "lon": 131.87353,
                    "pres": 1020.07,
                    "timezone": "Asia/Vladivostok",
                    "ob_time": "2020-03-03 08:15",
                    "country_code": "RU",
                    "clouds": 89,
                    "ts": 1583223350,
                    "solar_rad": 0.242723,
                    "state_code": "59",
                    "city_name": "Vladivostok",
                    "wind_spd": 0.260589,
                    "last_ob_time": "2020-03-03T07:30:00",
                    "wind_cdir_full": "Восточный-Юго-Восточный",
                    "wind_cdir": "ВЮВ",
                    "slp": 1026.22,
                    "vis": 24.1352,
                    "h_angle": 60,
                    "sunset": "09:03",
                    "dni": 2.77,
                    "dewpt": -6.2,
                    "snow": 0,
                    "uv": 0,
                    "precip": 0,
                    "wind_dir": 112,
                    "sunrise": "21:42",
                    "ghi": 0.49,
                    "dhi": 3.62,
                    "aqi": 39,
                    "lat": 43.10562,
                    "weather": {
                        "icon": "c04d",
                        "code": "804",
                        "description": "Облачно"
                    },
                    "datetime": "2020-03-03:08",
                    "temp": -2.7,
                    "station": "UHWW",
                    "elev_angle": 10.46,
                    "app_temp": -8.3
                }
            ],
            "count": 1
        }
    """.trimIndent()

}